### ISSUE TITLE
Adas enviada da exchange direto para endereço de stake pool , como recuperar?

### ISSUE THREAD

**Issue by ThallesZielinski** [vacuumlabs/adalite#1005]
Olá, por engano enviei minhas Adas direto da exchange para stake pool. Não entendo bem de ingles e depois que vizualizei o endereço correto da carteira para o qual deveria ter enviado.
Necessito da recuperação tendo em vista que foi para Stake Pool da ADALITE.

Me ajudem por favor!!!!

![Captura de Tela 2021-05-31 às 01 54 47](https://user-images.githubusercontent.com/85093672/120142457-b206db80-c1b4-11eb-838e-1362a09af30b.png)
![Captura de Tela 2021-05-31 às 01 56 46](https://user-images.githubusercontent.com/85093672/120142460-b3d09f00-c1b4-11eb-8607-b4f05e28b35e.png)
![Captura de Tela 2021-05-31 às 01 57 00](https://user-images.githubusercontent.com/85093672/120142465-b501cc00-c1b4-11eb-90d3-9ea262cf3a28.png)

**Comment by refi93** [comment]
Hi @ThallesZielinski - please contact the exchange and ask them to revert the transaction. Given the stake pool id is not a valid Cardano address, it's possible the transaction didn't happen and is still reversible by the exchange, but we can't guarantee that.

**Comment by ThallesZielinski** [comment]
Obrigado pelo retorno!

as adas voltaram pra corretora com status de transacao pendente, estou em contato para recupera-las.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em sexta-feira, 4 de junho de 2021 às 20:18, Rafael Korbaš ***@***.***> escreveu:
