### ISSUE TITLE
After firmware and Cardano ledger application upgrade, I can no longer connect.

### ISSUE THREAD

**Issue by stackBlock** [vacuumlabs/adalite#1009]
I was not able to connect because your website said I needed to update my ledger application. 
I Updated my application and the firmware and the application is still not connecting with this error, 
"**TransportError: Invalid channel. If you are using a hardware wallet, please make sure you are using the latest version of the Cardano application.**'

Is there something else I need to do? 

Thanks,
Anthony

nano info:

FIRMWARE: **2.0.0**
CARDANO APP VERSION: **2.3.2**

**Comment by refi93** [comment]
Hi @stackBlock - Can you also make sure Ledger Live or any other application/website interacting with Ledger is closed when you connect to Adalite?

Could you clarify what browser/operating system are you using?

**Comment by stackBlock** [comment]
Thanks for getting back to me so quickly... 

I am using Chrome Version 91.0.4472.77 (Official Build) (64-bit)
Windows 10 Home - Build 19043.1023

I just noticed that I seem to also be having issues with Daedalus connecting at the moment... So, this may be an issue on my side.  Let me try a few things and i will get back to you...

Thanks,
Anthony

**Comment by stackBlock** [comment]
Everything is working fine now... there must have been some interference with Daedalus or something...
sorry about that.

Have a good day!
