### ISSUE TITLE
API and DApps integration

### ISSUE THREAD

**Issue by dmitrystas** [vacuumlabs/adalite#1013]
Hi, AdaLite Team.

Is there any plans for API support and 3rd party Dapps integration, like MetaMask has

> The extension injects the Ethereum web3 API into every website's javascript context, so that dapps can read from the blockchain.
> 
> MetaMask also lets the user create and manage their own identities (via private keys, local client wallet and hardware wallets like Trezor™), so when a Dapp wants to perform a transaction and write to the blockchain, the user gets a secure interface to review the transaction, before approving or rejecting it.

?

**Comment by MichalPetro** [comment]
Hello,

we want to wait/work together on some standard with other major wallets (Daedalus, Yoroi). We would like to definitely support Cardano dapps, we don't yet how. The ideal case would be some common standard among wallets so dApps builders do not have to integrate with multiple wallets but they implement a single interface that will be able to communicate with any Cardano wallet.
