### ISSUE TITLE
can not connect to my wallet ledger NANO S

### ISSUE THREAD

**Issue by AMIRHOSEINRA** [vacuumlabs/adalite#1021]
when I go to my wallet show me this message
DeviceStatusError: General error 0x6e01. Please consult https://github.com/cardano-foundation/ledger-app-cardano/blob/master/src/errors.h

**Comment by refi93** [comment]
Hi Amir, please make sure you selected the Cardano app on your Ledger and "Waiting for commands..." appears on the screen. Then you should login without an error.

BTW: we just updated the error handling to show this suggestion for this error as we were able to replicate it under these conditions: https://github.com/vacuumlabs/adalite/commit/3cbe1e337db9cb769ac94b3838d68f7fa144989f
