### ISSUE TITLE
Ledger Nano S connection to AdaLite and Yoroi

### ISSUE THREAD

**Issue by tetraenter** [vacuumlabs/adalite#1022]
I can't connect my Ledger Nano S wallet to AdaLite and Yoroi wallets since 2 UTC.

**Comment by refi93** [comment]
Hi @tetraenter - could you please clarify what error are you getting? Does the problem persist?

**Comment by tetraenter** [comment]
Dear Rafael
The message i get when i select unlock with Ledger is adalite.io wants to connect to a HID device, i wait but it doesn't connect and finally, after some time i get the message:
Error loading wallet
Transport Canceled By User: Access denied to use Ledger device.

The exact same thing happens when i try to connect my ledger Nano S wallet to Yoroi. I have connected my device to AdaLite without any problem many times in past. My etherwallet works so i suppose that this is an Adalite or Yoroi error.
Ledger Nano S and Cardano Ledger app firmwares are up to date. All ad-blockers on AdaLite are disabledI have tried to initialize Ledger on AdaLite both in Chrome and Firefox browsers in Incognito(Chrome) mode but the results were the same.I have succesfully installed the WinUSB driver through Zadig to use the second unlock option without any results, the problem persists.
Thanks for your interest
tetraenter




    On Saturday, June 5, 2021, 09:39:57 PM GMT+3, Rafael Korbaš ***@***.***> wrote:  
 
 


Hi @tetraenter - could you please clarify what error are you getting? Does the problem persist?

**Comment by refi93** [comment]
I see - did you select the "Ledger Nano S" (or something similar) device with your mouse and then clicked "connect". Attaching screenshots highlighting what you should approximately see and what to click

![webhid_step_1](https://user-images.githubusercontent.com/4980147/120904500-eb27cb80-c64c-11eb-864a-a823f008faca.png)
![webhid_step_2](https://user-images.githubusercontent.com/4980147/120904503-ee22bc00-c64c-11eb-991c-fb7c167ad073.png)

Alternatively, you can try Firefox browser which doesn't trigger this prompt

**Comment by tetraenter** [comment]
Gosh, it was that simple, but i didn't notice! I didn't understand that it was a selection drop down menu, so i wasn't selecting Nano S as a device in order to activate the Connect button. It might be a point that needs enhancement through colouring, explaining or prompting to keep on with your excellent user interface!Thank you so much Rafael! Congratulations to you, AdaLite and our great Cardano community!
Best regards
tetraenter
    On Saturday, June 5, 2021, 11:27:43 PM GMT+3, Rafael Korbaš ***@***.***> wrote:  
 
 


I see - did you select the "Ledger Nano S" (or something similar) device with your mouse and then clicked "connect". Attaching screenshots highlighting what you should approximately see and what to click




Alternatively, you can try Firefox browser which doesn't trigger this prompt

**Comment by refi93** [comment]
solved via https://github.com/vacuumlabs/adalite/issues/779
