### ISSUE TITLE
Cannot connect Ledger Nano S to AdaLite

### ISSUE THREAD

**Issue by dks625** [vacuumlabs/adalite#1029]
I've had no problems in the past, but now I get the following error message:

"TransportInterfaceNotAvailable: Unable to claim interface. Please make sure that no other web page/app is interacting with your Ledger device at the same time."

I made sure to close Ledger Live and other Chrome windows, but the error message still comes up.

**Comment by MichalPetro** [comment]
Was this resolved? Are you sure you don't have active other apps possibly interacting with Ledger (Daedalus?)
