### ISSUE TITLE
Cant connect to adalite with ledger after reading previous post

### ISSUE THREAD

**Issue by Aldo333** [vacuumlabs/adalite#1036]
Hi,

I've had trouble opening my adalite wallet with ledger.

I've uploaded latest ada app version 2.2.1 and have used ledger with adalite many times before with no problems. Firmware version is 1.6.1 but there is no option to update and says it's up to date.

I open up manager in ledger live and select cardano app on nano s device. I select unlock with ledger at adalite.io. I then select the paired device in the window that comes up in adalite and click connect. The following error comes up... DeviceStatusError: Wrong Ledger app.

What are your thoughts? I appreciate any help.

Thanks

**Comment by refi93** [comment]
Hi @Aldo333 - did you also make sure to open the Cardano app on the device before connecting to Adalite? The wrong ledger app error is usually related to that.

Also please make sure to have Ledger Live or any other app potentially interacting with Ledger closed while interacting with Adalite, as Ledger can communicate only with one app/website at a time.

Regarding the firmware update not showing up, I'd recommend trying updating Ledger Live and if it still doesn't appear, I'd advise to contact [Ledger support](https://support.ledger.com/hc/en-us/articles/360006554854-How-to-contact-us). Their [article](https://support.ledger.com/hc/en-us/articles/360002731113-Update-Ledger-Nano-S-firmware) says it's a gradual release, but that may no longer be the case as it happened relatively long ago and/or they may know how to trigger the update in your case

**Comment by Aldo333** [comment]
Hey refi93

I did have ledger live open and that appears to be the problem. I always thought it was supposed to be open for synchronization to 3rd party wallet.

Still waiting for ledger support to get back to me about firmware update... but I got into adalite wallet..

Thanks heaps for your help mate! Much appreciated!!
