### ISSUE TITLE
cannot connect to ledger

### ISSUE THREAD

**Issue by adaadada44** [vacuumlabs/adalite#1038]
It is continually says "loading wallet data" on adalite, and continually says "Waiting for commands on ledger" at no point does my wallet load. Any ideas of what is going wrong?

**Comment by MichalPetro** [comment]
If you see s popup window similar to the one below, click on "Nano S/X" and click on "Connect" after. If this is not the case, please provide a screenshot of the screen where you see the Loadin Wallet Data message
![WebHID](https://user-images.githubusercontent.com/39809354/121742973-e22d7300-cb00-11eb-9a2e-cb5034b05bec.png)
