### ISSUE TITLE
can not connect to ledger

### ISSUE THREAD

**Issue by areid303** [vacuumlabs/adalite#1041]
comes up with adalite.io wants to connect to hid device but it never does

**Comment by MichalPetro** [comment]
Hello,

can you confirm that you select the device in the HID interface and click connect? See step 5 in this guide for details. https://github.com/vacuumlabs/adalite/wiki/How-to-use-Ledger-Nano-S-and-Nano-X-with-AdaLite

**Comment by areid303** [comment]
thank you.its all working now

________________________________
