### ISSUE TITLE
Error when signing pool transaction

### ISSUE THREAD

**Issue by kingtutPool** [vacuumlabs/adalite#1046]
When I connect Ledger nano x to adalite and try to sign a pool certificate I get the following error.

{"exception":{"values":[{"type":"TypeError","value":"Cannot read property 'map' of null","stacktrace":{"frames":[{"colno":27,"filename":"https://adalite.io/js/frontend.bundle.js","function":"async Object.signPoolCertificateTx","in_app":true,"lineno":93491},{"colno":38,"filename":"https://adalite.io/js/frontend.bundle.js","function":"Object.prepareTxAux","in_app":true,"lineno":91302}]},"mechanism":{"handled":false,"type":"onunhandledrejection"}}]},"level":"error","platform":"javascript","sdk":{"name":"sentry.javascript.browser","packages":[{"name":"npm:@sentry/browser","version":"5.22.3"}],"version":"5.22.3","integrations":["InboundFilters","FunctionToString","TryCatch","Breadcrumbs","GlobalHandlers","LinkedErrors","UserAgent"]},"event_id":"09a80b2476cc426db39702d84ef941ac","timestamp":1624143169.928,"environment":"production","breadcrumbs":[{"timestamp":1624142216.2195,"category":"ui.click","message":"div.wrap > div.page-wrapper > ul.tabinator > li.main-tab. > label"},{"timestamp":1624142216.2335,"category":"ui.click","message":"ul.tabinator > li.main-tab. > input#Staking[type=\"radio\"][name=\"tabs\"]"},{"timestamp":1624142217.0101,"category":"ui.click","message":"div.wrap > div.page-wrapper > ul.tabinator > li.main-tab. > label"},{"timestamp":1624142217.0274,"category":"ui.click","message":"ul.tabinator > li.main-tab. > input#Send[type=\"radio\"][name=\"tabs\"]"},{"timestamp":1624142217.1216,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142217.192,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142217.2668998,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142217.3327,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142217.433,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142217.4366,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142217.4884,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142217.4937,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142271.501,"category":"ui.click","message":"div.wrap > div.page-wrapper > ul.tabinator > li.main-tab. > label"},{"timestamp":1624142271.5149,"category":"ui.click","message":"ul.tabinator > li.main-tab. > input#Staking[type=\"radio\"][name=\"tabs\"]"},{"timestamp":1624142272.4887,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142272.7700999,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142272.8405,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142272.902,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142273.0110998,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142273.0115998,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142273.286,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142273.2889,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142338.7038,"category":"ui.click","message":"li.stake-pool-item > input.input.stake-pool-id[type=\"text\"][name=\"pool\"]"},{"timestamp":1624142338.8593001,"category":"ui.click","message":"li.stake-pool-item > input.input.stake-pool-id[type=\"text\"][name=\"pool\"]"},{"timestamp":1624142402.7628,"category":"ui.click","message":"div.dashboard.desktop > div.dashboard-column > div.delegate.card"},{"timestamp":1624142404.0893002,"category":"ui.click","message":"div.staking-balances-row > button.button.secondary.balance.refresh"},{"timestamp":1624142404.4658,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142404.5323,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142404.5953999,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142404.6608999,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142404.7077,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/info/e19723af4d479637a4c343853bdb1b05b23def9ddd779526c09054cfc6","status_code":200},"type":"http"},{"timestamp":1624142404.7568,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/delegationHistory/e19723af4d479637a4c343853bdb1b05b23def9ddd779526c09054cfc6","status_code":200},"type":"http"},{"timestamp":1624142404.7618,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/withdrawalHistory/e19723af4d479637a4c343853bdb1b05b23def9ddd779526c09054cfc6","status_code":200},"type":"http"},{"timestamp":1624142404.762,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/stakeRegistrationHistory/e19723af4d479637a4c343853bdb1b05b23def9ddd779526c09054cfc6","status_code":200},"type":"http"},{"timestamp":1624142404.8038,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/rewardHistory/e19723af4d479637a4c343853bdb1b05b23def9ddd779526c09054cfc6","status_code":200},"type":"http"},{"timestamp":1624142404.8573,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624142404.9047,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/poolRecommendation/poolHash/undefined/stake/0","status_code":200},"type":"http"},{"timestamp":1624142405.5280998,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142405.5288,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142405.5923998,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624142405.593,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624143091.901,"category":"ui.click","message":"div.wrap > div.page-wrapper > ul.tabinator > li.main-tab. > label"},{"timestamp":1624143091.9394,"category":"ui.click","message":"ul.tabinator > li.main-tab. > input#Accounts[type=\"radio\"][name=\"tabs\"]"},{"timestamp":1624143094.1933,"category":"ui.click","message":"nav.navbar.authed. > div.navbar-wrapper > button.button.secondary.logout"},{"timestamp":1624143094.296,"category":"navigation","data":{"from":"txHistory","to":"/"}},{"timestamp":1624143094.3021998,"category":"navigation","data":{"from":"/","to":"/"}},{"timestamp":1624143094.3275,"category":"ui.click","message":"div.authentication.card.initial > div.auth-options > div.auth-option.file"},{"timestamp":1624143096.2647,"category":"ui.click","message":"div.auth-options > div.auth-option.hw-wallet > h3.auth-option-title"},{"timestamp":1624143097.8646998,"category":"ui.click","message":"div > button.button.primary.ledger.thin-data-balloon.undefined"},{"timestamp":1624143098.8,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/v2/stakePools","status_code":200},"type":"http"},{"timestamp":1624143106.61,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143106.7155,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143106.8435,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143106.8511,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143106.9013,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/info/e13d6c5174326a2623daf0d68d4244fa427b4c15814d179a7923a55df6","status_code":200},"type":"http"},{"timestamp":1624143106.9413002,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143106.975,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/withdrawalHistory/e13d6c5174326a2623daf0d68d4244fa427b4c15814d179a7923a55df6","status_code":200},"type":"http"},{"timestamp":1624143106.9753,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/stakeRegistrationHistory/e13d6c5174326a2623daf0d68d4244fa427b4c15814d179a7923a55df6","status_code":200},"type":"http"},{"timestamp":1624143106.9967,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/delegationHistory/e13d6c5174326a2623daf0d68d4244fa427b4c15814d179a7923a55df6","status_code":200},"type":"http"},{"timestamp":1624143107.0005999,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/rewardHistory/e13d6c5174326a2623daf0d68d4244fa427b4c15814d179a7923a55df6","status_code":200},"type":"http"},{"timestamp":1624143107.0551999,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143107.0758998,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143107.1158001,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/poolRecommendation/poolHash/undefined/stake/0","status_code":200},"type":"http"},{"timestamp":1624143107.2188,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143107.314,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143107.3776,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/info/e1fbdaaa7332008d166f4fb56814b97e2e13c2ae8b6d51ccb02888694e","status_code":200},"type":"http"},{"timestamp":1624143107.431,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/delegationHistory/e1fbdaaa7332008d166f4fb56814b97e2e13c2ae8b6d51ccb02888694e","status_code":200},"type":"http"},{"timestamp":1624143107.4353,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/withdrawalHistory/e1fbdaaa7332008d166f4fb56814b97e2e13c2ae8b6d51ccb02888694e","status_code":200},"type":"http"},{"timestamp":1624143107.4363,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/stakeRegistrationHistory/e1fbdaaa7332008d166f4fb56814b97e2e13c2ae8b6d51ccb02888694e","status_code":200},"type":"http"},{"timestamp":1624143107.4763,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/rewardHistory/e1fbdaaa7332008d166f4fb56814b97e2e13c2ae8b6d51ccb02888694e","status_code":200},"type":"http"},{"timestamp":1624143107.5298,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143107.621,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/poolRecommendation/poolHash/dfaf8179da6abf63efa746fc62dd94925a03f0b13d77a0574a0ca6b8/stake/2271469470","status_code":200},"type":"http"},{"timestamp":1624143107.6511,"category":"navigation","data":{"from":"/","to":"txHistory"}},{"timestamp":1624143107.7250998,"category":"ui.click","message":"div.addresses.card > div.addresses-content > a"},{"timestamp":1624143107.8564,"category":"fetch","data":{"method":"GET","url":"https://min-api.cryptocompare.com/data/price?fsym=ADA&tsyms=USD,EUR","status_code":200},"type":"http"},{"timestamp":1624143109.9155998,"category":"ui.click","message":"section.welcome > div.welcome-footer > button.button.primary.wide.modal-button"},{"timestamp":1624143115.1048,"category":"ui.click","message":"div.wrap > div.page-wrapper > ul.tabinator > li.main-tab. > label"},{"timestamp":1624143115.1483998,"category":"ui.click","message":"ul.tabinator > li.main-tab. > input#Staking[type=\"radio\"][name=\"tabs\"]"},{"timestamp":1624143115.7875,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143115.8525,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143115.9174,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143115.9820998,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143116.0450997,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143116.1138,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1624143116.2207,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624143116.2219,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624143116.2861,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/utxo","status_code":200},"type":"http"},{"timestamp":1624143116.2867,"category":"fetch","data":

**Comment by PeterBenc** [comment]
Thnx for reporting the issue, we have already found the cause and are working on a fix.

**Comment by kingtutPool** [comment]
Thanks a lot , but I tested now and it is still the same , can you please confirm if it fixed or not yet ?

**Comment by refi93** [comment]
Sorry for not clarifying - the fix was merged into our develop branch but not yet released - we will release it into production tomorrow

**Comment by refi93** [comment]
@kingtutPool the fix has been released

**Comment by kingtutPool** [comment]
@refi93  Thanks a lot, working perfectly fine again , many thanks for your support .
