### ISSUE TITLE
I cannot connect to my ledger from Adalite

### ISSUE THREAD

**Issue by glyno1985** [vacuumlabs/adalite#1052]
I am getting this error message when I try to connect adalite wallet to ledger 
TransportCanceledByUser: Access denied to use Ledger device.

**Comment by refi93** [comment]
Did you make sure to close all other apps interacting with Ledger, especially Ledger Live?


Also do you have the Cardano app open in you Ledger device and is it showing the "Waiting for commands..." screen? Finally, when you click "Unlock with Ledger" in Adalite, you also need to confirm the public key export on the device as shown in the tutorial: https://github.com/vacuumlabs/adalite/wiki/Ledger-accessing-your-wallet

If this didn't help please share more details like the browser/OS you are using and what yo uexactly see in Adalite/Ledger while logging in so we can investigate further

**Comment by glyno1985** [comment]
Hi 

Thanks it works now

**Comment by Gustavocagi** [comment]
Hi
I've sent you a message to your email. Can you answer me?

> Did you make sure to close all other apps interacting with Ledger, especially Ledger Live?
> 
> Also do you have the Cardano app open in you Ledger device and is it showing the "Waiting for commands..." screen? Finally, when you click "Unlock with Ledger" in Adalite, you also need to confirm the public key export on the device as shown in the tutorial: https://github.com/vacuumlabs/adalite/wiki/Ledger-accessing-your-wallet
> 
> If these tips didn't help please share more details like the browser/OS you are using and what you exactly see in Adalite/Ledger while logging in so we can investigate further

Hi!.

**Comment by MichalPetro** [comment]
Answered by email
