### ISSUE TITLE
If I see my cryptos in adalite...

### ISSUE THREAD

**Issue by Gustavocagi** [vacuumlabs/adalite#1060]
Hi!

If I see my cryptos in adalite can I keep, receive and send them from adalite?.

If I see the balance of my cryptos in adalite can I send them from the Yoroi Wallet or Daedalus anywhere?. People say me that's possible. Is that correct?.

Thanks.

**Comment by MichalPetro** [comment]
Sorry Gustavo I am not sure I understand your question. But AdaLite seeds are usable also on Yoroi and Daedalus and vice versa.

**Comment by Gustavocagi** [comment]
Thanks.

Gustavo
