### ISSUE TITLE
I don't see my ADA coins

### ISSUE THREAD

**Issue by Hussain73** [vacuumlabs/adalite#1061]
Hi,
I am new to this ADAlite. I tried to transfer my ADA coins from NDAX account to my NANO X through ADALite. I copied the address from the receive tap and plugged it into NDAX and the coin has been withdrawn from NDAX. But I don't see the ADA balance in ADALite?

**Comment by refi93** [comment]
Hi, @Hussain73 withdrawals from exchanges may generally take longer to actually have effect, but for further details, you would need to contact NDAX support.

Do you have the hash of the transaction? If so, you can check in a block explorer (e.g. https://cardanoscan.io/) where exactly the funds went to (and if the destination address actually matches with the Cardano address of your Ledger, the funds should appear in Adalite too)

If you don't have the hash of the transaction, then only the NDAX support can help you as they are the ones having the information about the status of your withdrawal.
