### ISSUE TITLE
On win7 it failed to build with last installable Nodejs being v13.2

### ISSUE THREAD

**Issue by marxenegls** [vacuumlabs/adalite#1068]
On Windows 7 Nodejs v13.02 is the last installable version, could I edit the requirement - installed  yarn@1.22.10  via npm okay, trying to build it with VSCode;

error cardano@6.5.7: The engine "node" is incompatible with this module. Expected version "14.16". Got "13.2.0"
error found incompatible module.

is it yarn.lock that declares the dependencies, right ?
 The list is endless, too many things can go wrong...

 THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

**Comment by refi93** [comment]
The project is meant to be built on node 14.16 as the error suggests. You can try overwriting the "engine" setting in package.json with your version of node: https://github.com/vacuumlabs/adalite/blob/7c1ea6e4da431d9d08428a5febc359c2e8ba8491/package.json#L5 but it may or may not work. Alternatively, it seems that you can indeed force higher versions of node in Windows 7: https://stackoverflow.com/questions/62212754/nodejs-for-windows-7
