### ISSUE TITLE
Lost ADA in transaction (did not arrive at destination)

### ISSUE THREAD

**Issue by Jayqson** [vacuumlabs/adalite#1076]
Trans ID

c8a7c9357905db39afba0801375df3e89729b73b13b6e2fc853f2fcb771c2e78

Assist with recovering ADA please

**Comment by MichalPetro** [comment]
Can you elaborate please? Transactions are final and cant be canceled.

**Comment by Jayqson** [comment]
Transaction went through. My apology.
