### ISSUE TITLE
Prioritize in utxo selection utxos that contain the token to be sent

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#1077]
Problem: it seems we currently don't prioritize utxos containing the token to be sent when selecting them into the transaction, resulting in the behavior, that a token transaction contains a bunch of unrelated token inputs, which ultimately bloats transactions dealing with tokens

https://github.com/vacuumlabs/adalite/blob/307cbce574c7d061eac856383f4def13d18d152c/app/frontend/wallet/account.ts#L303-L308

**Comment by PeterBenc** [comment]
already fixed
