### ISSUE TITLE
Account shows negative reward balance

### ISSUE THREAD

**Issue by tdiesler** [vacuumlabs/adalite#1079]
https://cardanoscan.io/stakekey/aae3c82c51921ed9b88330a44a9be51813dda626cac71f66efe3d9b1

<img width="975" alt="Untitled" src="https://user-images.githubusercontent.com/244946/126463776-da1145c7-bfad-4f94-995e-4276fc24298a.png">

**Comment by xdzurman** [comment]
Thank you for raising this! We dug deeper into this and found out that the update of [one of cardano components](https://github.com/input-output-hk/cardano-db-sync/issues/696) we use has a bug concerning reward amounts, we are rolling back to an older version.
