### ISSUE TITLE
Update trezor integration to work after September 8th Trezor release

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#1103]
Trezor will soon have a release with Cardano memory optimizations so it can sign bigger transactions. This however led to returning just the witnesses instead of the full transaction body - similar to what Ledger does.

Here's the PR for trezor-connect https://github.com/trezor/connect/pull/841#pullrequestreview-737410729

This version of connect is backwards compatible with the current trezor FW and for the time being we can update adalite against a locally running instance of trezor-connect as described in https://wiki.trezor.io/Developers_guide:Running_Trezor_Connect_on_localhost

**Comment by edwardsous10** [comment]
Transfer its not working 

i tried to trasnfer from staking to regular wallet, what can i do?

**Comment by bleujj** [comment]
> Transfer its not working 
> 
> 
> 
> i tried to trasnfer from staking to regular wallet, what can i do?

Message trezorsuites@gmail.com for help

**Comment by gabrielKerekes** [comment]
@edwardsous10 Please create a separate issue describing your problem in more detail or use the [Adalite Telegram support channel](https://t.me/AdaLite). Definitely **do not** message trezorsuites@gmail.com as it's probably a scam e-mail. Watch out for scammers and if you are using Trezor then definitely never share your mnemonic phrase with anyone.

**Comment by refi93** [comment]
done
