### ISSUE TITLE
Can't connect with my Ledger X

### ISSUE THREAD

**Issue by mays23** [vacuumlabs/adalite#1104]
Hi!
I have paired my Ledger X to adalite.io, transferred my ADA to it and now I can't log in. It says "wrong ledger app". Pls help!

**Comment by MichalPetro** [comment]
Hello,

When did you access AdaLite with your Ledger for the last time?

Please make sure that all application that can interfere with your Ledger ale closed (such as Ledger Live) when accessing AdaLite

**Comment by PHinker** [comment]
I am having the same problem after upgrading the Ledger Nano X to version 1.3.0 and the Ada app to version 2.4.1

**Comment by kbentlage** [comment]
Had the same problem, you have to close Ledger Live! When it's active on the background it does not work.
