### ISSUE TITLE
It has been more than an 1 hour and I still have not recieved the ADA that sent to my Adalite wallet

### ISSUE THREAD

**Issue by Hava2021** [vacuumlabs/adalite#1109]
Hello,

I made two transfers to my Adalite wallet in succession. The first transfer went through really quickly. However, it has been more than an hour and the second transfer is still not reflecting in my Adalite wallet. I used the same address for both transactions. Please help, Thanks!

**Comment by MichalPetro** [comment]
Hello, received funds are reflected on AdaLite within minutes. The issue will be on the sender side.

**Comment by Hava2021** [comment]
Thanks, @MichalPetro, I have reached out to the people responsible on the sender side. I hope they will be able to help

**Comment by Hava2021** [comment]
@MichalPetro , the issue was indeed on the sender's side. Thanks
