### ISSUE TITLE
Trezore T Wallet without Mnemonic Code

### ISSUE THREAD

**Issue by HLB8888** [vacuumlabs/adalite#1129]
Please forgive me if I am not correct. I signed up for a Trezor T wallet and I do not remember Adalite giving me a Mnemonic key. My question is did I miss that in the sign up process or does the Trezor T wallet not provide a Mnemonic Key?
The reason I ask is the only log in option I currently have is with my Trezor T. If it was aver stolen, destroyed, or broken I have no understanding of how I would access my account. Can you please help me with a back up sign in option?
Thank you,

**Comment by MichalPetro** [comment]
Hi,
when you were setting up the Trezor, you set up a mnemonic phrase that is the key to all your funds on your Trezor (including Cardano). If your Trezor is lost or damaged, you just buy a new Trezor or restore the wallet in it using your Trezor mnemonic phrase. There is also Trezor emulator that can do this for you but it needs some technical knowledge.

**Comment by HLB8888** [comment]
Ahh, that makes sense. Thank you so much!!!
