### ISSUE TITLE
Problem with Trezor

### ISSUE THREAD

**Issue by dovgar** [vacuumlabs/adalite#1130]
Hi,
When I try to do Voting Registration I get the error:
"Transaction rejected while signing. Unexpected message"
The same error when I try to withdraw staking,
I am using Trezor ver 2.4.2
Thanks

**Comment by refi93** [comment]
Hi @dovgar - firmware 2.4.2 isn't AFAIK officially released yet and we can't support it until Trezor launches new connect which got delayed: https://github.com/trezor/connect/pull/841 - as soon as it is released, we can support also the new 2.4.2. FW - this should happen this week.

For the time being, I can advise you to downgrade the firmware back to 2.4.1: https://wiki.trezor.io/Firmware_downgrade

**Comment by Miaalexande** [comment]
> Hi,
> 
> When I try to do Voting Registration I get the error:
> 
> "Transaction rejected while signing. Unexpected message"
> 
> The same error when I try to withdraw staking,
> 
> I am using Trezor ver 2.4.2
> 
> Thanks
> 
> 

@dovgar Hello, Have you been attended to and have you been able to resolve out the issue yet ? Are you still experiencing any problems with your hardware wallet?

**Comment by refi93** [comment]
Adalite already supports FW 2.4.2 since version since https://github.com/vacuumlabs/adalite/releases/tag/v6.7.1 , closing
