### ISSUE TITLE
mnemonic phrase wallet & Trezor wallet

### ISSUE THREAD

**Issue by 0829777** [vacuumlabs/adalite#1138]
My mnemonic phrase wallet functions.
I am trying out my newly acquired Trezor wallet.

I was able to connect "an Adalite wallet" to the Trezor.  The Adalite wallet connected to the Trezor has 0 balance.

It is not the mnemonic phrase wallet that I created months ago.  

Where can I find guidance to connect the mnemonic phrase wallet to Trezor?

**Comment by MichalPetro** [comment]
You dont want to "connect mnemonic phrase to Trezor".

You want to generate a new wallet (mnemonic phrase) on your Trezor device securely and transfer the funds from your old wallet to the newly created Trezor wallet. For optimal security, your new Trezor wallet mnemonic seed phrase should be never used anywhere online.

**Comment by 0829777** [comment]
Thank you MP.  I am good to go.
