### ISSUE TITLE
How to switch from Yoroi wallet to Adalite wallet

### ISSUE THREAD

**Issue by Gustavocagi** [vacuumlabs/adalite#1139]
Hi!

I've a Yoroi wallet. Now it's the time of Alonzo update.

In any case I've tried to redelegate my cryptos and send some cryptos and It has been impossible. When I try to redelegate I press the button delegate I come back to the previous step. There's no message. And when I try to send some ADA the message is:" The message is it's happened unexpected. Try it again."

Several persons said me yesterday to change my wallet. How to do?. Is it easy?.

Thanks.

**Comment by refi93** [comment]
Hi @Gustavocagi - yes, switching from Yoroi to Adalite should be simple - if you have a mnemonic wallet in Yoroi (i.e. the 15-words seed phrase), you just log with it into Adalite (https://adalite.io) selecting the "mnemonic" option, if you have Ledger/Trezor, these options are available as well. In both cases you should see the same addresses/balance you see in Yoroi

**Comment by Gustavocagi** [comment]
Ok. Thanks.

Please, you don't close this issue. Your answer is very useful.

**Comment by Gustavocagi** [comment]
Hi refi93,

To switch from Yoroi to Adalite if I've Ledger have I to access my Cardano wallet or Create a new wallet?.

Thanks.

**Comment by MichalPetro** [comment]
You should use the Unlock with Ledger button. Dont create a new wallet (that will create a hot/mnemonic wallet)

**Comment by Gustavocagi** [comment]
Thanks.

**Comment by Gustavocagi** [comment]
> You should use the Unlock with Ledger button. Dont create a new wallet (that will create a hot/mnemonic wallet)

Hi Michal Petro,

Do you think I could with Adalite wallet to send, to redelegate and to withdraw ADA?. Now I cann't.

**Comment by MichalPetro** [comment]
Yes you can do all of thid.

**Comment by Gustavocagi** [comment]
Hi!

If my Ledger may freeze and will need to be reconnected can I use Adalite?
