### ISSUE TITLE
Can't submit transactions through adalite.io due to firewall blocking

### ISSUE THREAD

**Issue by liberdapps** [vacuumlabs/adalite#1141]
Hello. 

I`ve been trying to withdraw some staking rewards but noticed that, whenever I try to submit the transaction, I get an error saying that the network request failed. Digging into the failed request, I can see that it fails because the https://adalite.io/api/txs/submit URL is being blocked by the Sucuri Website Firewall.

For what is worth, I'm using the TOR browser, so it might have something to do. Odd enough, I have never had such an issue in the past. Is there any way to work that around? Thx.

**Comment by refi93** [comment]
Hi @liberdapps - we indeed recently enabled a new firewall on our end. I just modified the settings in a way that TOR traffic should no longer be impacted - could you try if it works for you?

**Comment by liberdapps** [comment]
Hi @refi93 ! Thanks for the quick feedback on this!

Okay,  I just retried a few times and, unfortunately, the issue is still present to me. I can access the front end and even see my balance, staking rewards, address list and other read-only information just fine. The issue seems to be with actual POST/PUT requests to the https://adalite.io domain. When I try to withdraw some staking rewards, I get an error message -- and I can confirm that the rewards are still available for withdraw on the block explorer.

Curiously, even POST requests to the https://explorer2.adalite.io subdomain work perfectly fine. It's just -- looks like -- the POST requests to the main http://adalite.io domain that seem affected.

If it helps, I'm posting these additional details about the failed request:

**Request:**

> POST /api/txs/submit HTTP/1.1
> Host: adalite.io
> User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate, br
> Referer: https://adalite.io/txHistory
> Content-Type: application/json
> walletType: Trezor
> walletVersion: 2.3.6
> walletDerivationScheme: v2
> txType: withdraw
> token: (hidden)
> Origin: https://adalite.io
> Content-Length: 815
> DNT: 1
> Connection: keep-alive
> 

**Response:**

> HTTP/2 403 Forbidden
> server: nginx
> date: Mon, 20 Sep 2021 14:55:09 GMT
> content-type: text/html
> x-sucuri-id: 14033
> x-xss-protection: 1; mode=block
> x-frame-options: SAMEORIGIN
> x-content-type-options: nosniff
> content-security-policy: upgrade-insecure-requests;
> x-sucuri-block: BLACK02
> X-Firefox-Spdy: h2
> 

This is the blocking error message I get:

> NetworkError: Request to our servers has failed. Please check your network connection and if the problem persists, contact us.


And when I try to open the failed request on a new tab, I get this:

> Access Denied - Sucuri Website Firewall
> URL: | adalite.io/api/txs/submit
> Your Browser: | Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
> Block ID: | BLACK02
> Block reason: | Your IP address is listed in our blacklist and blocked from completing this request.
> Time: | 2021-09-20 11:01:31
> Server ID: | 15033

Please, let me know if I can help debug this further and thanks again for looking into that! You guys rock!

Best.

**Comment by refi93** [comment]
@liberdapps interesting - could you try again? Now it should pass

**Comment by liberdapps** [comment]
@refi93 , awesome! Just tried it again and it worked great! 

I suppose that leaves this ticket as fixed :)

Thank you again.
