### ISSUE TITLE
Ledger may freeze. How can I reconnect it?

### ISSUE THREAD

**Issue by Gustavocagi** [vacuumlabs/adalite#1159]
Hi!

I've a Ledger may freeze how can I reconnect it?. Is  it possible with Adalite?.  At least to recover my ADA bought?

Thanks

**Comment by Gustavocagi** [comment]
Hi!
I'm out by job in Tchequie. I've not my desktop in front of me. I'll say you something next week.
I understand it depends of the problem you can give me a solucion or another. Doesn't it?

**Comment by refi93** [comment]
>  I understand it depends of the problem you can give me a solucion or another. Doesn't it?

correct
