### ISSUE TITLE
Error when sending tokens with amount bigger than 9,000,000,000,000,000

### ISSUE THREAD

**Issue by dorijan** [vacuumlabs/adalite#1163]
Hi to everyone.
It seems adalite cannot handle bigger number than 9,000,000,000,000,000, which is the limitation of js, so BigNumber library should be implemented to handle that numbers.

**Comment by refi93** [comment]
Hi @dorijan - thanks for raising this. You are right, this is indeed a known issue (#867) that we would like to address, but we were postponing it so far supposing that such high amounts are very unlikely to happen on mainnet. Do you know of some actual token that is impacted by this limitation? For the time being, as an alternative, you can use the Yoroi wallet which doesn't have such limitation
