### ISSUE TITLE
Invalid transaction file format error when loading pool signature file via adalite.io

### ISSUE THREAD

**Issue by jdh0812** [vacuumlabs/adalite#1200]
Hi,

I get this message when trying to load the offline pool registration certificate transaction form:

Parser error: Invalid transaction format. Invalid file structure. Make sure the JSON file has "type" and "cbor Hex" keys on the top level.

When  I google this  I get directed to this url

https://cardanoupdates.com/commits/bc84cef06bd80b1eea0a5f99d1af4ab5d67ca460

Which brought me to this github group.  I was wondering if this is a known issue that you're working on, or if maybe I'm doing something wrong?

Many Thanks

![image](https://user-images.githubusercontent.com/93354208/139345590-80387779-4cdc-4d08-8397-5138b5a820f1.png)
John H.

**Comment by refi93** [comment]
closed due to inactivity, feel free to reopen if needed
