### ISSUE TITLE
Error Loading Wallet

### ISSUE THREAD

**Issue by Beaverbruck** [vacuumlabs/adalite#1204]
I am not able to access my wallet from Daedalus.  I paired my Ledger S to the Daedalus wallet.
Today, I tried to access my wallet in adalite.  I have been opening my Ledger S in Ledger Live then closing Ledger Live. I have the Cardano app open on the device.  I then open Adalite and try to connect my ledger S.   I keep getting the error message which reads:  DeviceStatusError:  General error 0x6e01.  Please make sure that the Cardano Ledger App is opened before initiating the collection.  I'm running Windows 10.  Ledger Live is running the most recent version(2.34.2) and just two days ago I uninstalled and the reinstalled Cardano App. ver. 2.4.1 I tried this on Google Chrome as well as Microsoft Edge and tried everything on two different computers. What am I doing wrong?  I really need some help.  It seems as though, it doesn't recognize that the app is open in the Nano S.  Thanks

**Comment by refi93** [comment]
Hi @Beaverbruck, as the error suggests, you not only need to install the Cardano app, but you have to  select and open it on your Ledger device. Moreover, the Ledger Live app must be closed when interacting with Adalite, otherwise it interferes with your Ledger device, making the connection with Adalite fail. The Ledger device can interact only with one app at a time

**Comment by Beaverbruck** [comment]
Thank you for taking the time to respond to this problem.  I thought that when I brought up the Cardano app on my Nano S that I was in the app.  I was not in the app, only on the app.  Once I confirmed, everything when fine.  I was able to access my wallet.  However, there was a problem with my staking rewards and I was not able to get them.  Thank you so much for taking the time to assist me.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by MichalPetro** [comment]
can you elaborate? what is the issue with staking rewards?

**Comment by Beaverbruck** [comment]
This is the message I got this morning.  I just went  back into the wallet and got the same message.

09/13/2021
Possibly missing rewards in staking history

One of the cardano components we use may be missing some of the rewards. For this reason, staking history and CSV exports may be wrong. However, your staking balance is unaffected by this issue and you can freely withdraw your correct amount of rewards.

Looks like the problem has been here for a while.  It’s dated 9/13/2021.  I went into the staking section and my rewards balance is there, but the available balance is zero.  I clicked the refresh button, but nothing changed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>


Sent: Sunday, October 31, 2021 1:11 PM
To: ***@***.***>
Cc: peter ***@***.***>; ***@***.***>
Subject: Re: [vacuumlabs/adalite] Error Loading Wallet (Issue #1204)


can you elaborate? what is the issue with staking rewards?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vacuumlabs_adalite_issues_1204-23issuecomment-2D955751950&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=YNR1KbcNsggHUoSzBe6fno1BL4wBi2YLx7jnqs9fEyg&m=vfyB0Q77uL_PXUJ8OEo2SXJ7Veqv4nOb59clF_17W9s&s=AO8yxhgiFHe92t8WjGGJQsqoUi7vrBnHDymwWh-ttkM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWI7LEUXXLT6SARUJM2C7ZDUJV2DXANCNFSM5HBPC5VQ&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=YNR1KbcNsggHUoSzBe6fno1BL4wBi2YLx7jnqs9fEyg&m=vfyB0Q77uL_PXUJ8OEo2SXJ7Veqv4nOb59clF_17W9s&s=dICSW5ZMb0idEBFdeyic2Oz9-vPUitrOP_rPrI_NPuA&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=YNR1KbcNsggHUoSzBe6fno1BL4wBi2YLx7jnqs9fEyg&m=vfyB0Q77uL_PXUJ8OEo2SXJ7Veqv4nOb59clF_17W9s&s=JM1lL3MAW4Xwxr6-DtSHigfDqdxAlUGLgPm0Rmy0y-4&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=YNR1KbcNsggHUoSzBe6fno1BL4wBi2YLx7jnqs9fEyg&m=vfyB0Q77uL_PXUJ8OEo2SXJ7Veqv4nOb59clF_17W9s&s=0yyLttGj7iFMq-f1JzGXIu_3PqbuN8gYdcoVBfl5_r4&e=>.

**Comment by Tristantro** [comment]
Trouble in Adalite and then WMT vault

1. sending from account 2 to another adalite wallet 
2. transfering from account 2 to account 1
3. transaction failed message but my ADA is gone and not in the other walletas well

finally i cannot connect to Adalite wallet due to :

"Network error: request to connect to our servers has failed. Please check your network connection and if the problem persist, contact us."

where is the support? here ?

what is happening, have i lost my 3175 dollar worth of ADA ?
![failed to connect to wallet adalite](https://user-images.githubusercontent.com/91091656/143266535-99994f87-f692-4f19-8e9e-b9f4a673f819.jpg)
?

**Comment by Tristantro** [comment]
> Trouble in Adalite and then WMT vault
> 
> 1. sending from account 2 to another adalite wallet
> 2. transfering from account 2 to account 1
> 3. transaction failed message but my ADA is gone and not in the other walletas well
> 
> finally after logging out i cannot connect to Adalite wallet due to :
> 
> "Network error: request to connect to our servers has failed. Please check your network connection and if the problem persist, contact us."
> 
> where is the support? here ?
> 
> what is happening, have i lost my 3175 dollar worth of ADA ? ![failed to connect to wallet adalite](https://user-images.githubusercontent.com/91091656/143266535-99994f87-f692-4f19-8e9e-b9f4a673f819.jpg) ?
![server error adalite](https://user-images.githubusercontent.com/91091656/143272390-1889261a-6416-4810-9216-2aee6d94eda6.jpg)


how is it possible that the servers are down when it is a distributed network?

all servers can not be down, or?

do we need to setup more nodes or what do we need to do?

im a supernoob, but thats okay 🥇 👯

**Comment by refi93** [comment]
Hi @Beaverbruck sorry for the late reply. The message you are referring to is a general warning referring to the service we are fetching the history from. You can read more on it in our wiki: https://github.com/vacuumlabs/adalite/wiki/Known-issue-with-missing-rewards
