### ISSUE TITLE
Sending Ada to my KuCoin wallet

### ISSUE THREAD

**Issue by Ofeka11** [vacuumlabs/adalite#1205]
Hey, 
I sent an hour ago 2600 Ada to my KuCoin Ada wallet. I see it been confirmed over the Blockchair.com and the funds should be in my wallet. I can’t see them and it makes me nervous. Please reply as soon as possible!! 
I been reading and I should have 0 problems.

**Comment by MichalPetro** [comment]
Hello,

please reach out to KuCoin support. If your funds arrived on the KuCoin deposit address it is up to KuCoin to credit them.

**Comment by Ofeka11** [comment]
It been taken care, thank you

בתאריך יום א׳, 31 באוק׳ 2021 ב-19:10 מאת MichalPetro <
***@***.***>:
