### ISSUE TITLE
My wallet Ledger no connect Adalite

### ISSUE THREAD

**Issue by Zoommann** [vacuumlabs/adalite#1224]
until recently everything still worked,
I can currently no longer access my account.
Enclosed the error message, can you please help me, thank you.
[AdaLite.docx](https://github.com/vacuumlabs/adalite/files/7581553/AdaLite.docx)

**Comment by goldieben** [comment]
Hi!

Thank you for contacting AdaLite. For assistance, please open a support ticket here: https://support.nu.fi/support/tickets/new. 

Sincerely,
Ben
AdaLite Support Team
