### ISSUE TITLE
Getting error " Does Not Support Model 1" using Model T and running Firmware 21.11.2

### ISSUE THREAD

**Issue by zingsthings** [vacuumlabs/adalite#1233]
Everything is up to date but for some reason it is thinking Im running a model 1 Trezor even though I am running the latest Model T.
My Model T opens my other wallets fine just not my adalite wallet all of a sudden. Any suggestions?

**Comment by tsusanka** [comment]
@stew790 @bosomt could you try to reproduce this with latest TT version on adalite.io?

**Comment by bosomt** [comment]
**QA OK**

@tsusanka i had no problem to login to ADA wallet with current public firmware version 2.4.2

<img width="1019" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/144053421-40115da2-b188-490b-ae87-9eac715c5cf7.png">

**Comment by matejcik** [comment]
@bosomt would you mind trying a bunch of lower FW versions? say, 2.3.x (whichever you have on hand), 2.4.0 and 2.4.1

**Comment by bosomt** [comment]
**QA OK**

**2.3.4**
https://cardanoscan.io/transaction/a6cc8a6cccedf355e763979097a211b920443ebf8b9d58d78d3bcfab6198d137
https://adaex.org/a6cc8a6cccedf355e763979097a211b920443ebf8b9d58d78d3bcfab6198d137

**2.4.0** 
https://cardanoscan.io/transaction/c6bc375e972cb497d7d0c0c40d3f1f79cf1c8bf88fca48cfffddbbab671d60d7
https://adaex.org/c6bc375e972cb497d7d0c0c40d3f1f79cf1c8bf88fca48cfffddbbab671d60d7

**2.4.1**
https://cardanoscan.io/transaction/c2112e3a17b3d4c0a0bbdabc5711e0b35ec494fef1387b103fef45f6a07d3218
https://adaex.org/c2112e3a17b3d4c0a0bbdabc5711e0b35ec494fef1387b103fef45f6a07d3218

**Comment by bosomt** [comment]
@zingsthings can you please record your Trezor issue including this status page ? http://127.0.0.1:21325/status/

**Comment by zingsthings** [comment]
I am sorry for the error on my part. I own both the Model 1 and model T. I was using the Model 1 when attempting to log in.
