### ISSUE TITLE
Ada gone from ada.lite 

### ISSUE THREAD

**Issue by Karischm** [vacuumlabs/adalite#1234]
Hi, I just logged into my trezor and then to adalite to send some ada to the exchange and now everything is gone.

How is that possible? I staked ada and sent funds several times.

Hope someone can help me out.

Thank you and BR,
Kari

**Comment by goldieben** [comment]
Dear Kari,

Thank you for contacting AdaLite. For assistance, please open a support ticket here: https://support.nu.fi/support/tickets/new. 

Sincerely,
Ben
AdaLite Support Team

**Comment by goldieben** [comment]
Hello again Kari,

Just to clarfiy, you can use the link I posted before or you can open a support ticket by clicking Contact Us at the bottom of the page on AdaLite.io. You can also use the email address shown there. 

Sincerely,
Ben
AdaLite Support Team
