### ISSUE TITLE
Missing ada

### ISSUE THREAD

**Issue by msmoneyworth** [vacuumlabs/adalite#1235]
Logged into my wallet and my ada is missing. Tried to file a ticket from the link in the comments of the last person with this issue but I kept getting an error msg.

**Comment by goldieben** [comment]
Hello!

This is Ben from AdaLite Support Team. Can you please open a support ticket using the contact form on AdaLite? The best way to do this is to go to the bottom of the page (on AdaLite.io), click Contact Us, and then describe the problem. Please also tell me how you access your wallet (i.e. with a mnemonic/seed phrase or with a Ledger/Trezor). 

Best,
Ben
AdaLite Support Team
