### ISSUE TITLE
please help: wallet not loading with trezor after new firmware

### ISSUE THREAD

**Issue by CryptoLeo** [vacuumlabs/adalite#1236]
my Trezor T  worked perfectly with adalite until yesterday. today I installed the new firmware and now I can't access my wallet: AdaLite says "error loading wallet" (servers down or network error). I also tried with Yoroi and Nami: It loads the wallets but I can't confirm any transaction, as it says there is an error occurring.
I think this is a problem related to new firmware(?), do I have to set something also to solve the problem?

**Comment by refi93** [comment]
Hi @CryptoLeo , we apologize for the inconvenience - unfortunately, due to an elevated rate of hardforks on the chain we;ve been experiencing intermittent server downtimes today. We already fixed it and they are up again. Let us know if you need any more assistance

**Comment by Spider942321** [comment]
I'm having similar issue, but this is the prompt I get:

TrezorError: Trezor operation failed, please make sure ad blockers are switched off for this site and you are using the latest version of Trezor firmware. Cannot read properties of null (reading 'postMessage')

is this the same issue and what are some possible solutions for this? thank you
