### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by jinhozzang** [vacuumlabs/adalite#1237]
Hello

After creating a Mnemonic account through AdaLite, it was possible to log in normally until 18:00 KST today, but,

When logging in from around 19:00 KST, a pop-up window appears as below and you can't access it.

Please check the cause and take action.

[Pop-up story]

Error loading wallet

NetworkError: Request to our servers has failed. Please check your network connection and if the problem persists, contact us.

**Comment by refi93** [comment]
Hi @jinhozzang , we apologize for the inconvenience - unfortunately, due to an elevated rate of hardforks on the chain we;ve been experiencing intermittent server downtimes today. We already fixed it and they are up again. Let us know if you need any more assistance
