### ISSUE TITLE
Where the mnemonic  stored

### ISSUE THREAD

**Issue by Tindtily** [vacuumlabs/adalite#1244]
I read the readme , but i can't understand where the mnemonic stored.   If i logout, the mnemonic will be leaked?

**Comment by MichalPetro** [comment]
Hello, AdaLite wallet does not have persistent memory. You need to always enter the mnemonic if you want to access it and therefore it is mostly used by users with Hardware Wallets. If you want to use more convenient way to manage your mnemonic, I would recommend using the new wallet that we launched just yesterday - HTTPS://nu.fi/
