### ISSUE TITLE
AdaLite.io voting damaged PNG QR code file

### ISSUE THREAD

**Issue by GaryCrowstick** [vacuumlabs/adalite#1250]
AdaLite.io voting damaged PNG QR code file.
Hey there, I have downloaded the QR code for voting five times and it's always corrupted. It will not open using preview on a mac. It can not also be converted online into a jpeg or pdf. I just can't open the QR code to scan using Catalyst whatever I try.
Is this a bug? 
Thanks

**Comment by DavidTranDucVL** [comment]
I couldn't replicate this issue on any system. If the problem persists feel free to reopen the issue with more detailed information.
