### ISSUE TITLE
0 balance and different address after restore

### ISSUE THREAD

**Issue by Malejhoch** [vacuumlabs/adalite#1251]
Hi,
I have problem with restore my wallet. 
I used Trezor T, after some hardware failure I buy Ledger X and try restore my wallet. I put my seed phrase from Trezor T to new Ledger. Some other tokens works (XLM), but when I try connect with HW wallet ADA wallet on adalite.io somethings is wrong. I restore different address with 0 balance and no history. It´s same if I use Yoroi.

Can you help me to access to my tokens?
Thanks.

**Comment by refi93** [comment]
Hi @Malejhoch , Ledger and Trezor default derivation schemes (i.e. the way of deriving keys from a mnemonic) for Cardano are unfortnuately different meaning the same mnemonic would yield on Ledger different keys/addresses than on Trezor which is also the behavior you described. The differences are documented in the following CIP: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/README.md

If you want to safely retrieve the Cardano funds of your Trezor wallet, you will unfortunately have to buy another Trezor T device, as Ledger simply isn't interoperable with Trezor in the case of Cardano.

An alternate, less safe approach that works for 12 word Trezor mnemonics could be to recover the wallet directly from the mnemonic on certain software wallets that happen to derive the keys/addresses the same way as Trezor does - AFAIK such wallets currently are https://nu.fi and https://typhonwallet.io  - this approach however has the downside that you expose the mnemonic on your computer and hence it could no longer be considered safe to use with a hw wallet, not even for the other coins held there. Moreover without an additional hw wallet it will require considerable effort to safely move the remaining coins (e.g. XLM) to the new mnemonic (recover Ledger from a new mnemonic, write down the addresses of the new wallets, recover Ledger from the old mnemonic, move the funds except Cardano to the new addresses and then go on to import the mnemonic into NuFi/Typhon to access and send the Cardano funds)

For 24-word Trezor mnemonics, the only way I know of apart from buying the actual device would be to setup the Trezor emulator on your computer (works for MacOS/Linux): https://docs.trezor.io/trezor-firmware/core/emulator/index.html and initiate the emulated Trezor with your mnemonic - this has the same security downside as the approach described above for 12 word mnemonics
