### ISSUE TITLE
Issue with withdrawing staking rewards

### ISSUE THREAD

**Issue by AdaBob** [vacuumlabs/adalite#1267]
When trying to withdraw staking reward, shows "transaction pending" that hangs indefinitely.
Reward is not withdrawn into my account.

Thank you.
jon.

**Comment by AdaBob** [comment]
This is when using a Trezor...

**Comment by MichalPetro** [comment]
Hi Jon,

Cardano network is currently congested. It can take for the transaction up to 60 minutes to execute.

**Comment by AdaBob** [comment]
Never happened AT ALL.  I tried 4x.
I timed out every time.

-jon

**Comment by AdaBob** [comment]
This ONLY began happening after the Adalite upgrade.

**Comment by MichalPetro** [comment]
Which upgrade?

We are trying to solve this situation but unfortunately, all wallets are encountering this issue. Currently, almost all transactions are confirmed within 60 minutes after submission.

**Comment by AdaBob** [comment]
Are you saying that you need to wait an hour for the rewards to be transferred to your wallet?   It doesn’t go through at all.

Adalite or Trezor had a recent upgrade about a month ago.  Before that, this never happened.

Thanks,
Jon

**Comment by AdaBob** [comment]
I heard there was a protocol update. So maybe for that reason it takes so long?

Why would that be?

Thanks,
Jon

**Comment by MichalPetro** [comment]
The reason is that the Cardano blockchain is congested.
