### ISSUE TITLE
Delegation on second account not working

### ISSUE THREAD

**Issue by moenchj** [vacuumlabs/adalite#1270]
When trying to redelegate to another stakepool on Account #2, The delegate button stays disabled and the fee calculation does not seem to work.
On Account #1 everything works as expected.
![Untitled](https://user-images.githubusercontent.com/38103680/152341606-7deeca30-5dde-4e46-bf90-9166f322a9ca.jpg)

**Comment by DavidTranDucVL** [comment]
Hi, are you still experiencing this issue? Also, are you sure that there wasn't any other transaction pending at the time?
