### ISSUE TITLE
Someone stole my coin

### ISSUE THREAD

**Issue by Trilbee** [vacuumlabs/adalite#1276]
I was holding a small amount of ADA on AdaLite.io secured with my Ledger.
On 28th Jan it was transferred out without my knowledge.
How can this happen without authorisation from my Ledger?

**Comment by MichalPetro** [comment]
Hello, can you share your address? You can send it to our support email together with link to this issue.

info@adalite.io

This is actually not possible.

**Comment by Trilbee** [comment]
What address do you need?

**Comment by MichalPetro** [comment]
any address of your wallet
