### ISSUE TITLE
Transaction history export for Koinly

### ISSUE THREAD

**Issue by P3rz1val** [vacuumlabs/adalite#1279]
I don't see a way to export a CSV of all transaction history. I'd like to use this to prepare a tax return using Koinly. Is it possible to generate such a file?

**Comment by goldieben** [comment]
Hello, @P3rz1val!

You can export transaction history (send/receive) from the Send tab, on the left-hand side under Transaction History. This doesn't include rewards, though; for rewards history, you can use pooltool.io to query your wallet's address and display all rewards received by epoch in an easy-to-view table that you can then export as a CSV file -- please see this video for details:
https://www.youtube.com/watch?v=qCCCqwKeaxQ

Let me know if you need further assistance. 
Best,
Ben
