### ISSUE TITLE
cardano.explorer shows wrong balance

### ISSUE THREAD

**Issue by Karlaz** [vacuumlabs/adalite#1296]
Hello. When I use my wallet regurarly with device connected to pc and application, everything is fine but when I want check balance using address with wallet offline (eg in cardano e3xplorer) it shows much lower balance then is my real value. What is wrong? I tried several pages and value always wrong. Todays it is first time I came to this issue.

**Comment by MichalPetro** [comment]
Your funds are most likely dispersed among multiple addresses. If you are using Cardanoscan to view your address - check the field "Controlled Total Stake" - this should show funds on all addresses associated with your wallet.
