### ISSUE TITLE
Stuck on "Waiting for Commands..." while connecting with my Ledger Nano S

### ISSUE THREAD

**Issue by Makkev1** [vacuumlabs/adalite#1300]
stuck on "Waiting for Commands..." while connecting with my Ledger Nano S
Hi There i can't acces my wallet it keeps waiting for command on my ledger, i have the new update filmware  2.1.0 and the ada app is 3.0.0. i also tride to connect with Connect with WebUSB but that doesn't work. i use chrome browser and it's up to date. please let me know how i can get in my wallet? i have Windows 10 Home.

thanks for your help!
Kind regards Mark

**Comment by goldieben** [comment]
@Makkev1 
Hello Mark,

I've just received your email with screenshots and I replied with the following (to your email, but I'm copy/pasting it here for your reference):

===
Dear Mark,​

Thank you for the update.

In the top-left box (the one created by your browser, shown in image 1 that you attached) where you see the words 'Nano S' at the top, and 'Connect' and 'Cancel' at the bottom, please click on the words Nano S: this will make the 'Connect' button active. If you click that, your device should connect. From there, you'll need to interact with the device to export the public keys.

Please try that and let me know how it goes.

Best,
Ben
AdaLite Support Team

**Comment by goldieben** [comment]
@Makkev1 
That's great! I'm glad you got it working. Don't hesitate to contact me if I can help with anything else.

Best,
Ben
AdaLite Support Team
