### ISSUE TITLE
Latoken Collaboration Proposal

### ISSUE THREAD

**Issue by hr5085541** [vacuumlabs/adalite#1307]
Hi ADA Lite team,

I represent a Centralized Exchange - Latoken. I am a Listings Manager. We are keen to list your token on our exchange.

Our key value-adding services are:

1. Token Listing
2. Token Adoption through co-marketing activities
3. Reach Millions of traders and social community
4. IEO Crowdfunding to raise funds
5. NFT Airdrops to attract users

Would you be interested to know more? Probably, have a 10 minutes call?

Please book a meeting with this link: https://calendly.com/hasnain-raza/meeting-with-hasnain-from-latoken

**Comment by refi93** [comment]
Hi @hr5085541 sorry for the late reply and thanks for reaching us - Adalite doesn't have any token therefore we aren't interested in this. For future collaboration proposal, please reach us preferably via email
