### ISSUE TITLE
I cannot connect to ADALITE.

### ISSUE THREAD

**Issue by KJOTC** [vacuumlabs/adalite#1315]
I have been unable to connect to ADALITE since last Friday.
I received the following message on the site, so I checked the network and it is working fine.

”NetworkError:Request to our servers has failed. Please check your network connection and if the problem persists, contact us.”

So I don't know how to solve this problem.
Has there been an update on ADALITE recently?
When I try to connect several times, the connection sometimes succeeds.

**Comment by KJOTC** [comment]
I use it with my Trezor Wallet.

**Comment by MichalPetro** [comment]
Hi, can you please describe what steps did you take before seeing this error? What exactly happens after you click on the "Unlock with Trezor" button?

**Comment by KJOTC** [comment]
I got this error after I entered my passphra on Trezor.

"Please enter your passphrase." Is displayed.

**Comment by goldieben** [comment]
@KJOTC Thank you for the update. So that we can investigate this further, could you please share with us a receiving address for each of your Trezor wallet's Cardano accounts?

**Comment by goldieben** [comment]
@KJOTC
When you share with us the receiving address(es), can you also please tell me:
- did you use the wallet before the Shelley era (June 2020)? 

Also, I'd suggest trying NuFi; this will help us to see if it's an AdaLite-specific issue. To do this, please navigate to https://wallet.nu.fi, create a new wallet and attempt to pair your Trezor device. Please let us know if you encounter similar problems or if the problem exists only on AdaLite.
