### ISSUE TITLE
”NetworkError:Request to our servers has failed. Please check your network connection and if the problem persists, contact us.”

### ISSUE THREAD

**Issue by LockJames81** [vacuumlabs/adalite#1316]
Hi first time using this so I hope someone can help me.

I recently have tried to connect my Nano Ledger S Wallet to adalite.io as have been staking my Cardono cypto for approx a year but unfortunately I havent been able to access my account.  I keep getting the following error message.

”NetworkError:Request to our servers has failed. Please check your network connection and if the problem persists, contact us.”

- I connect my nano s ledger wallet as per usual
- click both buttons down
- the screen says "waiting for commands"
- I then click on Hardware Wallet (recommended)
- Unlock with Ledger

But then get error message

Ive tried changing all methods and repeating but no joys

Am I doing something wrong?? What do I need to do or is it something your side?

**Comment by goldieben** [comment]
@LockJames81 
Thank you for contacting AdaLite. When you say, "I've tried changing all methods and repeating but no joy" I assume you mean the different connection methods in the dropdown menu under the Unlock button. If not, please try this.

Could you also please try using a different browser and -- if you have one to hand -- try accessing AdaLite from another device?

If the above fails, please let me know here or by contacting me through the helpdesk at help@adalite.io

**Comment by LockJames81** [comment]
Nope still not working. Ive always used Google Chrome is that not compatible anymore?

**Comment by goldieben** [comment]
@LockJames81 Thank you for the update. I'm speaking to a developer now about this and I'll contact you again shortly.

**Comment by goldieben** [comment]
@LockJames81
I've spoken to a developer and the error message you see has a few possible causes, so it would help us a lot if we can identify the specific request that's causing it. It would be very helpful if you could do the following:
1. Press F12 to open the developer tools in Chrome
2. Connect to AdaLite and try to unlock your wallet
3. Download the report from the network tab in developer tools by clicking the button shown in the image I've included, and send this to me via help@adalite.io (so the information contained remains private)
![image](https://user-images.githubusercontent.com/91193850/174791681-dfaf1ef6-078c-47f7-9d38-22a23abb784b.png)
