### ISSUE TITLE
Unable to access AdaLite wallet from Firefox

### ISSUE THREAD

**Issue by jboyer3** [vacuumlabs/adalite#1320]
Currently running on Manjaro (Arch) - Firefox was working previously. 
STR - 
Connect Trezor wallet
Unlock wallet with PIN
open https://atalite.io - click hardware wallet - click unlock with Trezor
TrezorConnect.io opens in new tab, loading spins, window closes, adalite.io page spins a sec, new TrezorConnect page opens - sticks spinning on Loading. 

Popups allowed for both domains, ABP disabled for both domains, site data/cookies cleared for both domains. 
Further, accessing via Chrome works as expected.

**Comment by refi93** [comment]
Hi @jboyer3 - thanks for your report, I was able to replicate the issue and I forwarded the report to Trezor devs to investigate it further: https://github.com/trezor/trezor-suite/issues/5749

**Comment by jboyer3** [comment]
Understood, thanks for following up!

**Comment by refi93** [comment]
@jboyer3 as mentioned in https://github.com/trezor/trezor-suite/issues/5644 the fix for now is toggling "enhanced tracking protection" off for adalite.io in Firefox
