### ISSUE TITLE
MISSING ADA

### ISSUE THREAD

**Issue by Stam249** [vacuumlabs/adalite#1338]
I transferred ADA to my trezer using AdaLite about 8 months ago, I checked about a month after doing the transfer and it was all there now I check today and nothing any help?

**Comment by goldieben** [comment]
Hello @Stam249,

Thank you for contacting AdaLite. Are you currently using the Passphrase feature on your Trezor? Or, if not now, were you using it when you last accessed the wallet?

**Comment by daniceDev** [comment]
@Stam249 Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.
