### ISSUE TITLE
Minhas Ada's não estão na carteira

### ISSUE THREAD

**Issue by adarafa** [vacuumlabs/adalite#1376]
Está havendo alguma instabilidade no sistema da Adalite.io? pois meu saldo está zero.

**Comment by refi93** [comment]
Hi @adarafa sorry for the late reply, if your problem persists, please contact our support via the contact form at the bottom of the adalite website (https://adalite.io) Most likely you've entered a different mnemonic or if you have hardware wallet, you may have accidentally activated the passphrase feature
