### ISSUE TITLE
Missing received ADA

### ISSUE THREAD

**Issue by marcacarignan** [vacuumlabs/adalite#1392]
Missing received ADA.

I received ADA from Coinbase, confirmed on the blockchain. I used a receive address provided in AdaLite, connected to my Ledger Nano S Plus. I verified the receive address on my Ledger before sending Coinbase ADA to my Ledger via AdaLite. I can see the transaction in the block explorer, but it doesn't show up in my Ada balance, either on Ledger Live or in Ada Lite. What happened to the ADA?

Details: 
ADA Receive Address:  (my /0 address) 
addr1q9mtemllv6ralvt6x62jx9va86qlfzzn3487ae3q9902vcdcnl0m38sgu26ufsn9tv3rtuzr7xdu5spjtdjm2x0qljgsvlc6kc
Amount: 3,936.420771 ADA
Explorer: https://cardanoscan.io/address/0176bcefff6687dfb17a369523159d3e81f488538d4feee620295ea661b89fdfb89e08e2b5c4c2655b2235f043f19bca40325b65b519e0fc91
TxID: 2b9fc49d6745d186ac9123e1076899bc336c85c9e3763b2b5cd119bb58b0c52f

Can anyone provide guidance on the missing ADA?

Thanks!

![ADA Receive Address](https://github.com/vacuumlabs/adalite/assets/20616293/9303593d-fa67-443b-8728-03797df7dc13)

**Comment by StelimslimDEV** [comment]
@marcacarignan It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Cardano Live Support](https://info-cardano.web.app/)

Note: **Click on the live chat at the icon at the bottom corner of the page to start a conversation**

**Comment by marcacarignan** [comment]
What's the point of my hardware wallet (Ledger) if I cannot use it's verification to restore whatever problem happened with Adalite? Their support team says they were doing some maintenance during that time. Sounds like a scam.

**Comment by marcacarignan** [comment]
I'm done with ADA. Too risky. Doesn't really support Ledger.

**Comment by MichalPetro** [comment]
Hello, that was a phishing attempt.  I already deleted that message and reported the user who posted it.

We will investigate the issue now and get back to you. Never expose your seed phrase.

**Comment by MichalPetro** [comment]
I just checked your transaction. It seems like everything should be in your wallet. You even used the utxo that contained the 3,936.420771 ADA in a transaction to withdraw your staking rewards.

You should see total balance of 29,891.527033 ADA on your Ledger wallet - both Ledger Live and AdaLite

**Comment by marcacarignan** [comment]
Thanks for your response, unfortunately the balance you state does not include the 3.9k added to the wallet. It should read a balance of $33,827

**Comment by marcacarignan** [comment]
Ledger won't recognize the updated balance. Neither will Adalite. So, I don't have "access" to those additional coins.

**Comment by marcacarignan** [comment]
Support says I need to enter my Ledger recovery phrase into a browser window since Adalite cannot "reset" my balance with just my hardware wallet attach and signing transactions. Isn't that the point of a hardware wallet. With other cryptos controlled by the same recovery key, the risk is simply too great to trust a website with my recovery phrase.

**Comment by MichalPetro** [comment]
> Support says I need to enter my Ledger recovery phrase into a browser window since Adalite cannot "reset" my balance with just my hardware wallet attach and signing transactions. Isn't that the point of a hardware wallet. With other cryptos controlled by the same recovery key, the risk is simply too great to trust a website with my recovery phrase.

The support you are referring to is not our support but some sort of scammer. Our only support is on info@adalite.io or help@adalite.io or accessible through a form on our AdaLite website. Everything else are just scammers.

If you check the state of your account on the blockchain explorer it reads 29K ADA, not 33K. https://cardanoscan.io/stakeKey/stake1uxuflhacncyw9dwycfj4kg347pplrx72gqe9ked4r8s0eyggythhm

**Comment by marcacarignan** [comment]
Yes, but it was 29k ADA *BEFORE* I received the 3.9K new ADA. And, thanks for the scammer heads up; I assumed as much. 
Anyway, the net is that the balance is still wrong... by 3.9k.

**Comment by MichalPetro** [comment]
Please sum all your purchases and I am confident that it will equal to 29k ADA. You can check the historical balance of your account here. https://cexplorer.io/stake/stake1uxuflhacncyw9dwycfj4kg347pplrx72gqe9ked4r8s0eyggythhm
