### ISSUE TITLE
adalite.io is blocked

### ISSUE THREAD

**Issue by edpgcooper** [vacuumlabs/adalite#1393]
Hi, My IP seems to be blocked from accessing to adalite.io, any ideas how I get this resolved?

**Comment by refi93** [comment]
Hi @edpgcooper, I suppose you are getting blocked by our Cloudflare site protection. If so, I'd suggest trying the following:
1. incognito mode
2. different browser
3. switching to a different internet provider (e.g. internet from the cellphone)
4. try clearing the site data (guide for chrome: https://www.guidingtech.com/clear-chrome-cookies-cache-one-site-only/)

If the problem persists please provide more details, i.e. the exact error you are getting, and we can look into it. In case of Coudflare blocking, sharing the "ray id" shown on the error page would help us pinpoint the exact issue
