### ISSUE TITLE
missing ADA in my wallet

### ISSUE THREAD

**Issue by debduo** [vacuumlabs/adalite#1394]
How do I see where my coins went to?
Thanks for your help.

**Comment by refi93** [comment]
Hi @debduo you should be able to see your wallet movements in the "Transaction History" section upon loading your wallet. More detailed guidance can be found in this wiki: https://github.com/vacuumlabs/adalite/wiki/Troubleshooting#i-dont-see-my-funds-when-i-log-into-adalite

If you still have questions, please contact our support via the "contact us" link at https://adalite.io
