### ISSUE TITLE
Voting with Catalyst app does not work for me "wallet cannot be found"

### ISSUE THREAD

**Issue by draschke** [vacuumlabs/adalite#1414]
Voting: 
Everything works until the voting fee is transferred.

When I display the QR code afterwards and try to authenticate my wallet via the Catalysator app, I get the message that the wallet cannot be found.

If I save the BarCode and try to connect to the wallet with the app via the BarCode, nothing happens. 

The Catalyst app has been updated to the latest version.

**Comment by goldieben** [comment]
@draschke Thanks for reaching out. Some users in the past have reported some success in dealing with such issues when removing and re-installing the voting app; if you registered successfully and got the necessary pin and QR code, then you can be sure that you're eligible, but it's hard for us to advise on troubleshooting because we're not involved in the running or development of the voting app; have you tried asking in the Catalyst groups on Telegram or Discord?

**Comment by draschke** [comment]
Thank you very much for the quick response.

Yes, I have also informed Catalyst about this and am now in contact with the team.

I have uninstalled and reinstalled the app.  
However, the problem persists. "Wallet not found"

I'm surprised that I'm the only one having the problem.

**Comment by goldieben** [comment]
@draschke Can you please tell me what date you registered for voting? Was it before the deadline on June 18th?

**Comment by draschke** [comment]
@goldieben 
16.6. 
21.6.
25.6.
The behaviour was always the same

**Comment by goldieben** [comment]
@draschke Okay; from what I understand, you completed the voting registration process on AdaLite (which includes entering a pin, creating a transaction, getting the QR code) on the 16th; what was your account's ADA balance on the 18th of June, which is when the snapshot was taken?

**Comment by draschke** [comment]
@goldieben
More than 500 Ada's. Sorry, for the large pic. ;)
![image](https://github.com/vacuumlabs/adalite/assets/4199123/df22cf83-01b8-4594-89cb-4a8cc5c21a67)

**Comment by goldieben** [comment]
Thanks for the update @draschke. I see 3 x transactions there in your wallet history: is this 3 x attempts at registering on AdaLite? When you try to link your wallet on the Catalyst Voting app, are you using specifically the pin + QR code that you set up on the first attempt? (which was before the eligibility snapshot was taken on the 18th, i.e. within the allowed registration period)

**Comment by draschke** [comment]
@goldieben 
> I see 3 x transactions there in your wallet history: is this 3 x attempts at registering on AdaLite?
Yes, exactly.

In my opinion, I have always had to enter a PIN for each QR code.
I did this every time and always used the same one in all three cases.

**Comment by goldieben** [comment]
@draschke I asked previously about using specifically the first QR code generated, which was on the 16th, because only the QR code generated on this day will work, since the other two were generated on days after the voting registration period ended. The pin can be the same each time (since you set this) but the code generated is different each time. You'll need to link your wallet on the Voting app using the QR code created on the 16th; do you have access to this?

**Comment by draschke** [comment]
@goldieben 
> You'll need to link your wallet on the Voting app using the QR code created on the 16th; do you have access to this?

Great, that has now worked. Thank you very much!

Yes, luckily I had saved the QR code at the time.

Of course I'm very pleased that it has now worked!
However, I'm still confused as to why the transaction isn't cancelled if the deadline has passed.

But these are certainly things that have to be done via the Catalyst app.
The QR code scan via the app also took a very long time without any information being displayed that the process was still in progress in the background.

Anyway, as I've already said, I'm glad that it works! :)

**Comment by goldieben** [comment]
@draschke Great, glad you got it working!

The Catalyst voting registration transactions (sent from Adalite when you go through the registration process) are essentially regular Cardano transactions with metadata, so there's no reason for them to be cancelled.

Importantly: these later transactions (more exactly, the last one) still count as valid registrations for the next Catalyst round (invalidating the older registrations), so you need to make sure to scan the latest QR code in the Catalyst app when you participate in the next round OR just re-register in Adalite when it's time to do that in the next Catalyst fund, and use the QR code generated at that time instead.

**Comment by draschke** [comment]
Thank you very much!

In general, I would like to be informed during the payment process which voting you are actually paying for.
And when downloading the QR code, I would like this information to be set as standard when saving.
Thank you very much for your support!
