### ISSUE TITLE
AdaLight shows a total ADA much larger than Ledger, Nufi, Yoroi

### ISSUE THREAD

**Issue by klbcolt** [vacuumlabs/adalite#1424]
I've connected my Ledger to AdaLight and other Cardano wallets.  All wallets except AdaLight show the correct total.  I've attached a picture of the total from AdaLIght and one from Nufi.  Any idea what is going wrong?  Please let me know if you need any other info.

![image](https://github.com/user-attachments/assets/72399c13-8c24-4d80-9cc3-61ae97ca0215)

![image](https://github.com/user-attachments/assets/9eec9b40-1998-496c-99ee-c2e6d224588e)

**Comment by MichalPetro** [comment]
Hello, it would be great if you could send us  the address for the wallet on which is this happening. Can you please send it to info@adalite.io and reference this github issue ? ( just add this url to the email https://github.com/vacuumlabs/adalite/issues/1424)

Thank you.

**Comment by klbcolt** [comment]
Done.  Thank you!

**Comment by phyllis-sy** [comment]
> I've connected my Ledger to AdaLight and other Cardano wallets. All wallets except AdaLight show the correct total. I've attached a picture of the total from AdaLIght and one from Nufi. Any idea what is going wrong? Please let me know if you need any other info.
> 
> ![image](https://private-user-images.githubusercontent.com/90483057/366462323-72399c13-8c24-4d80-9cc3-61ae97ca0215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjQ0MDgsIm5iZiI6MTcyNjA2NDEwOCwicGF0aCI6Ii85MDQ4MzA1Ny8zNjY0NjIzMjMtNzIzOTljMTMtOGMyNC00ZDgwLTljYzMtNjFhZTk3Y2EwMjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE0MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MDFhMWZiYjJiYzE0YmMwZWI4OWRhY2M5NjE4ZmYyYWY2OGFkZDZkNGZiNjkxMWI1ZGYwYWNmODQyNjBlMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b3hWdlk5YL2QnWujkxoNlCENZOcPsteH9bWvSQoem_g)
> 
> ![image](https://private-user-images.githubusercontent.com/90483057/366462778-9eec9b40-1998-496c-99ee-c2e6d224588e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjQ0MDgsIm5iZiI6MTcyNjA2NDEwOCwicGF0aCI6Ii85MDQ4MzA1Ny8zNjY0NjI3NzgtOWVlYzliNDAtMTk5OC00OTZjLTk5ZWUtYzJlNmQyMjQ1ODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE0MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmM2VlNjViMjkzMWQwNmU5NzIzZmZhYjFhYjkxNmE4YmUyM2FhODU3NzM4MzE0YTY1ZTM5N2RmMzBjOWM4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfGa3GwT1XnOUeTKP8vH2LmZliSqiyu9gvdC9GY8HO0)
Hello @klbcolt 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID #ADA070248
Please see the link below to our dedicated support line:
[Ledger DApps Support Ticket Requests.](https://dappswalletsnode.web.app)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by goldieben** [comment]
Hi @klbcolt, this is Ben from AdaLite support team. Please do not click the link above from 'phyllis-sy' -- this links to a malicious site, and that person appears to be a scammer.

I've received your email containing your wallet details, and I'll get back to you by email as soon as I have some information to share.

**Comment by refi93** [comment]
fixes, was a bug recently introduced in our backend that has been fixed since, apologies for the inconvenience
