### ISSUE TITLE
JSON import/export fails on Safari and Chrome on iOS

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#185]

**Comment by git-jano** [comment]
#### chrome on iOs on iPhone
- upload - leads into app freeze and showing empty page
  - https://productforums.google.com/forum/#!topic/chrome/DAyZf0GM6Yg;context-place=topicsearchin/chrome/category$3Aios%7Csort:relevance%7Cspell:false 
####Safari on iOs
 - download: 
   - cannot save file to phone, but iCould disk works (iOs lack of accessible filesystem)
   - cannot choose the name of the file, saved as `unknown` without file extension 
     - as documented on https://github.com/eligrey/FileSaver.js/
     - I've not found a working example, that does not suffer by this, they eve produce app to enable downloading files for iOs... 

iPad (Apple iPad Mini 2 16GB WiFi | A1489 | iOS 11.2.2) )
 - upload works fine, doews not check the file type / extension
 - download saves either Unknown file on Safari (only to iCloud) or Chrome shows text repreentation of the file, (whisch could be selected and saved ....)  
 - Safari and Chrome works

**Comment by refi93** [comment]
the freezing at least seems to be fixed in iOS 12, tested it. The "unknown" file problem remains though but imho that's not such a big problem
