### ISSUE TITLE
Setting ELB sticky session cookie for blockchain explorer not working

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#195]
The Amazon ELB sends a "sticky-session" cookie (set-cookie=AWSALB=....) in the header of the response from the blockchain explorer, but the client does not send it back in the following requests. This means that the client does not have the guarantee to get consistent data (the response from two different blockchain explorer instances may differ), which may result in glitches in balance, e.g. right after performing a transaction, since the explorer instances behind the ELB may not be both fully synced.

**Comment by jennylialiu** [comment]
Like

**Comment by refi93** [comment]
fixed
