### ISSUE TITLE
TrezorConnect: adaGetAddress vs cardanoGetAddress, etc.

### ISSUE THREAD

**Issue by prusnak** [vacuumlabs/adalite#197]
It seems you've taken rebranding a little too far. I've found 4 occurrences of this issue:

https://github.com/vacuumlabs/adalite/blob/5d8b4b2aca1a9e188298ac96574dc819ffe02d94/app/frontend/wallet/cardano-trezor-crypto-provider.js#L37

https://github.com/vacuumlabs/adalite/blob/5d8b4b2aca1a9e188298ac96574dc819ffe02d94/app/frontend/wallet/cardano-trezor-crypto-provider.js#L105

https://github.com/vacuumlabs/adalite/blob/5d8b4b2aca1a9e188298ac96574dc819ffe02d94/app/frontend/wallet/cardano-trezor-crypto-provider.js#L147

https://github.com/vacuumlabs/adalite/blob/5d8b4b2aca1a9e188298ac96574dc819ffe02d94/app/frontend/wallet/cardano-trezor-crypto-provider.js#L229

There are no `TrezorConnect.ada*` methods, only `TrezorConnect.cardano*` methods.

Or am I missing something?

**Comment by refi93** [comment]
@prusnak yes, this was an error introduced by the rebranding and fixed later when the the transition to the new derivation scheme was made, as you can see from the history of the file you are referencing: https://github.com/vacuumlabs/adalite/commits/master/app/frontend/wallet/cardano-trezor-crypto-provider.js

**Comment by prusnak** [comment]
Ok, I was not able to find the fix earlier.

For reference: this has been fixed in 738e0ce2af2d197e2018f7637b6b8ebbc9351bc2
