### ISSUE TITLE
Update Trezor link

### ISSUE THREAD

**Issue by MichalPetro** [vacuumlabs/adalite#231]
Update old link to Trezor tab https://adalite.io/app#trezor to 
https://adalite.io#trezor

**Comment by jonathancross** [comment]
Hi @MichalPetro, both links you listed seem to work fine.  Am I missing something?

**Comment by MichalPetro** [comment]
Hi @jonathancross, you are right, I didn't check it when creating the issue (we did small changes link structure but I didn't realize it didn't have any impact on this link). Thanks for reaching out.
