### ISSUE TITLE
Update disclaimer

### ISSUE THREAD

**Issue by MichalPetro** [vacuumlabs/adalite#232]
Please update disclaimer. Format the text in some nice way, if absolutely necessary, add scroll bar so the text is scrollable.

https://docs.google.com/document/d/1ob-QQzNEuMj2FpXJw6Xt7bugYcsqqoOExjZmJuUHzf0/edit?usp=sharing

**Comment by mirecmrozek** [comment]
Would this be acceptable, or should i polish it more?
![image](https://user-images.githubusercontent.com/41968972/48484980-e80f2a80-e817-11e8-907b-3637471e37f3.png)

**Comment by refi93** [comment]
I think it's good enough for now, but I would wait for @MichalPetro 's opinion

**Comment by mirecmrozek** [comment]
I tried tweaking different things like `font-size`, color of all text, color of bold text, i tried using a list... None of which improved my impression of the disclaimer.
I talked with Michal on slack and he agrees to use this version.
