### ISSUE TITLE
Rework footer

### ISSUE THREAD

**Issue by MichalPetro** [vacuumlabs/adalite#234]
Update footer

- [x] so that it is always on the bottom of the page (unless the content pushes it down) - like on main page https://adalite.io/

- [x] change the twitter hyperlink name to "Twitter"

- [x] Increase size of the font of social media hyperlinks

- [x] Decrease the font of Crypto compare line

- [x] Make sure that cryptocompare line displays in footer only on history screen

**Comment by refi93** [comment]
In the "Export screen" the footer is too big
![untitled](https://user-images.githubusercontent.com/4980147/48301933-5dbc8300-e506-11e8-9c5a-20e397537e32.png)
