### ISSUE TITLE
PGP Signed commits & releases

### ISSUE THREAD

**Issue by jonathancross** [vacuumlabs/adalite#240]
Users of AdaLite should be able to verify that the software they are running is the same as you created.  This should be independent of of github, etc.  In most professional cryptocurrency wallets, developers use `gpg` to sign their code commits and release engineers sign versioned releases. This includes desktop wallets like Bitcoin Core, Electrum and web-based wallets like the [Monero Paper wallet generator](https://github.com/moneromooo-monero/monero-wallet-generator/).

Would be great if AdaLite could also begin making official releases here on GitHub and signing them.  Signing commits with the same key would also be great as it demonstrates that the devs building the project also stand by the release.

**Comment by MichalPetro** [comment]
Thanks @jonathancross for pointing out. We will research best practices and deploy improved process for release management.

**Comment by jonathancross** [comment]
Fantastic!  Please let me know if I can help clarify anything.
I know gpg can be very frustrating to work with, but it is the best we have right now  :-)

**Comment by refi93** [comment]
@jonathancross we just started gpg signing releases which will take effect from 1.1.0 release onwards: https://github.com/vacuumlabs/adalite/releases The core contributors (i.e. also the ones making releases) are expected to set up properly their gpg signatures. Therefore the tags of the releases would be always signed, as well as the commits made by core contributors. Here is summed up our release workflow: https://github.com/vacuumlabs/adalite/blob/develop/RELEASES.md Do you have any suggestions on further improving it?

**Comment by refi93** [comment]
closed by #252 and #255
