### ISSUE TITLE
Fix modals in Firefox on smaller screens

### ISSUE THREAD

**Issue by mirecmrozek** [vacuumlabs/adalite#244]
On smaller screens in Firefox, only the middle part of the disclaimer is visible, is not scrollable, close button is out of view and closing via clicking on empty space around doesn't work, which locks user from using our site.
For reference, this is what it looks like on a common mobile viewport 
![screen shot 2018-11-16 at 11 12 36](https://user-images.githubusercontent.com/41968972/48615272-b7063580-e990-11e8-972e-35eef121b5bf.png)
update: going through the app I see that it's a problem with all modals, so I'm going to create a common modal component that will solve this problem.

**Comment by refi93** [comment]
closed by #249
