### ISSUE TITLE
Error during walet initialization - display more explanatory error message if fails

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#288]
We could display something like "fetching data from blockchain explorer failed" in case we detect it's a network error. This would help some people figure out whether they have just connectivity problems (so they don't contact us unnecessarily) or if it is somewhere else.

**Comment by bigamasta** [comment]
@refi93, is this only about showing the message "fetching data from blockchain explorer failed" instead of "Error during wallet initialization" that's currently present? Thanks!

**Comment by refi93** [comment]
@bigamasta it's about telling a network error from other errors, so this issue involves also interpreting the exception and showing the network error only if the error is actually related to the network, otherwise the generic error message should be still shown. So it's not just replacing the error message.

**Comment by bigamasta** [comment]
I was just about to create PR, but I found out that there's already a branch with work done on this issue.
Please check https://github.com/vacuumlabs/adalite/compare/develop...i-288-better-error-message-for-wallet-initialization-failure?expand=1 and let me know if it needs further work. Thanks!
