### ISSUE TITLE
Add readonly mode

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#304]
A read-only mode would allow users to monitor the funds of a wallet without actually plugging the hardware wallet or inserting the mnemonic. There could be the option to export the wallet public key as a json, same as we currently offer the option to export the private key.

This would also allow creating unsigned transactions and signing them in offline mode, mentioned in #476.

A possible flow could look like this:
1. user opens adalite offline, generates a new mnemonic
2. user selects "export public key", saves it as a JSON to a USB drive/QR code
3. user goes to adalite online, imports the public key, he sees the wallet balance
4. user creates a transaction and exports it alongside the data needed to a JSON
5. user takes the JSON, e.g. by a USB key to the offline PC and signs the transaction there
6. user takes the signed tx to the online computer and sends it

**Comment by jmuravsky** [comment]
covered in #718
