### ISSUE TITLE
Make use of new backend submit tx endpoint

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#363]
Currently we are using a custom endpoint to submit transactions (https://github.com/vacuumlabs/adalite/blob/develop/server/transactionSubmitter.js) which does the raw tcp communication. This can be replaced with this endpoint: https://github.com/vacuumlabs/adalite-backend-service/blob/76c38ad021204b242745c1362c12c2ccf94791d4/src/routes.js#L209

**Comment by j-matus** [comment]
Done in #365
