### ISSUE TITLE
Visual bugs from meeting

### ISSUE THREAD

**Issue by darjanin** [vacuumlabs/adalite#376]
- [x] paddings on pages
- [x] footer & content padding
- [x] remove focus on Access demo wallet
- [x] change margin on dashboard’s header to 48px 
- [x] remove transitions on buttons
- [x] scrolling on transactions history (n items and half item with white shadow to hide) *only on desktop*
- [x] scrolling on addresses *only on desktop*
- [x] on select dropdown show options under selected item
- [x] add border on login screen for mobile
- [x] align button on login to the left
- [x] add export to menu on mobile
- [x] tooltips missing on the balance. add it using text under information instead of hover.
- [x] change title on my addresses 
- [x] show balance on all screens - this more question. we can leave it at the moment

**Comment by d-novak** [comment]
Tooltips on balance -> created separate issue #379
