### ISSUE TITLE
Refactor state handling in crypto providers

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#383]
Currently there is created a "local" state by object assign in each of the crypto providers (e.g. here: https://github.com/vacuumlabs/adalite/blob/develop/app/frontend/wallet/cardano-trezor-crypto-provider.js#L6), but this is a misleading abstraction since this "local" state is actually the global one. It would be more straightforward to just use the global state and not pretend there is any local state. The other option would be creating a true local state or a less misleading abstraction, but I don't see any at the moment.

**Comment by jmuravsky** [comment]
no longer relevant
