### ISSUE TITLE
Implement testing feedback

### ISSUE THREAD

**Issue by d-novak** [vacuumlabs/adalite#404]
- [x] "raw unsigned transaction" link is not disabled when the address/amount/fee are missing
- [x] "max" button is clickable when the address is missing, but max amount cannot be computed without knowing the output address (which influences the final transaction size and therefore the fee), therefore it should be disabled when the address is missing or incomplete/invalid
- [x] when I click on an address from "My Addresses" that takes more than one line, only the line I clicked on is selected
- [x] When verifying an address on trezor, the "Verify on trezor" link on the modal should be disabled, ideally being replaced by a text "Waiting...", until the user actually confirms the address. Clicking again on the "Verify on Trezor" link results in closing the modal which is not desired.
- [x] When I confirm the transaction, the screen gets stuck on the transaction summary modal until the tranaction is submitted. The expected behaviour after confirming the transaction is seeing a spinner describing the state of the transaction being submitted.
- [x] The raw unsigned transaction in the modal should be wrapped into multiple lines instead of being in a single very long line
- [x] the question mark next to the eur/usd balance does nothing when I click on it, probably should be removed
- [ ] I tried turning off the server shortly before submitting a transaction which results in a network error, but the UI doesn't show any error, it just empties the address and amount of ada from the "Send ADA" section after confirming the transaction
- [ ] In the login screen, when clicking on "Unlock" button I see no error message suggesting that the mnemonic is missing or invalid (I think this feature was there in a previous version of design 2.0)
- [ ] I see no error message when loading the wallet from mnemonic and the network fails, the spinner just disappears without further notice. It's replicable by running the wallet in mocking mode (enable the ADALITE_ENABLE_SERVER_MOCKING_MODE flag, which redirects network requests through the dev server) and turning off the server just before loading the wallet. When I insert an arbitrary 27-word mnemonic which also results in an error (an unrelated bug, not expected to be fixed there, but good for the sake of getting an error while loading the wallet), it gets stuck on the spinner. These behaviours point at missing or incomplete error handling in the code.

**Comment by refi93** [comment]
closed by #406
