### ISSUE TITLE
Ledger Blue support

### ISSUE THREAD

**Issue by timothyBrake** [vacuumlabs/adalite#449]
The Ledger support team mailed me to contact the developers so here I am expressing interest in this feature.
There seems to only be support for Ledger Nano S. 
Any chance on supporting Ledger Blue?

**Comment by refi93** [comment]
@timothyBrake Unfortunately, we are not aware of any plans to add Cardano support to Ledger Blue. Given that the product is not being sold anymore, the chances are very slim.
