### ISSUE TITLE
Trezor connection error (in chrome)

### ISSUE THREAD

**Issue by ortexx** [vacuumlabs/adalite#452]
I am trying to connect with Trezor Model T and i get an error:

`builder.js:107 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://connect.trezor.io') does not match the recipient window's origin ('null')`

The error is in chrome (v73). Everything works fine in firefox.

**Comment by refi93** [comment]
@ortexx I was not able to reproduce it on 73.0.3683.86 on MacOS.

Do you have Adblock or another potentially "problematic" extension enabled? Are you able to use MyEtherWallet (https://www.myetherwallet.com/) with Trezor on Chrome? Does it happen in incognito mode as well?

Maybe the suggestions in this issue may help you: https://github.com/stripe/react-stripe-elements/issues/98

**Comment by ortexx** [comment]
Yes, this is due to some extensions. Thanks!
