### ISSUE TITLE
I can not enter the wallet. trezor t

### ISSUE THREAD

**Issue by ghost** [vacuumlabs/adalite#471]
I can not enter the wallet. trezor t. win 7.
![ggg](https://user-images.githubusercontent.com/51291771/58762296-57036500-8557-11e9-9b6a-37ab09efc87a.png)

**Comment by refi93** [comment]
@ghost are you able to use it with https://myetherwallet.com? Does this happen in incognito mode as well? If not, I would recommend you to turn off your adblocker.
