### ISSUE TITLE
Transaction error - submitting the transaction error into Cardano network failed. 

### ISSUE THREAD

**Issue by pankrats** [vacuumlabs/adalite#482]
Chrome browser
Adalite Ver. 3.3.11

Hardware device - Trezor T (latest firmware 2.1.1)

I am receiving "Transaction error - submitting the transaction error into Cardano network failed. " after signing the tx with Trezor device. I am trying to send money to myself, to one of the Addresses of the unlocked wallet. 

Steps to reproduce:
1. Unlock a wallet with Trezor
2. Select one of the addresses from "My Addresses", fill it in Send ADA form, fill in the amount, click Send
3.  Confirm the tx on the Trezor device

Result: getting this error in AdaLite
<img width="1037" alt="Screenshot 2019-06-19 at 16 44 51" src="https://user-images.githubusercontent.com/31442634/59776471-28a1bb80-92b3-11e9-8bdd-86e58c7065e3.png">

Sometimes the result is a bit different (I am not sure yet, what exactly causes it): 

<img width="985" alt="Screenshot 2019-06-19 at 16 50 15" src="https://user-images.githubusercontent.com/31442634/59776883-dd3bdd00-92b3-11e9-9a6b-0e8d53aa56dd.png">

It seems like the tx is generated and signed correctly, but then the error happens on the AdaLite site.

**Comment by refi93** [comment]
@pankrats thanks for the report, we were able to reproduce it and we are looking into it right now

**Comment by refi93** [comment]
@pankrats seems like the error is not related to Trezor, but one of our servers went into an inconsistent state, refusing to process new transaction submissions. Now it should be working again.

**Comment by williampeartree** [comment]
Hi - I am having the same issue, however I am using a Ledger Nano X. Google Chrome, Ada Lite 6.6.0.

I can perform transfers normally however the issue arises when I am trying to withdraw my staking rewards.

**Comment by nmcbride** [comment]
I am also having the same issue as @williampeartree.
