### ISSUE TITLE
Validate password when exporting wallet mnemonic

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#499]
Currently there are no constraints on the password for the exported wallet mnemonic, which allows the user to set even "dumb" passwords for the file which does not seem very safe.

It would be nice to require it to have at least 8 charactes, use at least one uppercase and lowercase letter and at least one numerical digit (a subset of NIST guidelines: https://en.wikipedia.org/wiki/Password_policy)

**Comment by tomaskulich** [comment]
Please don't do this. IMO the standards are completely idiotic. If you want to implement some requirement, let's validate only the pwd's length.

**Comment by MichalPetro** [comment]
We wont enforce but we will recommend
