### ISSUE TITLE
dateFrom param not working

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite#519]
Looks like the adalite legacy api `api/v2/txs/history` hasn't the `dateFrom` param working? I'm not able to filter returned txs by `dateFrom`.

Edit: I just discovered that for example if a tx has date `1568388391000`, putting as `dateFrom: 1568388391000 + 1` would still show the tx. But If I sum like 7 seconds, it won't show the tx (that's the wanted behavior). So the question is why do I need to add like 7000 ms?

**Comment by refi93** [comment]
sorry for the delay, moved the issue to the backend repo since this is a backend-related issue, moved to: https://github.com/vacuumlabs/adalite-backend-service/issues/62
