### ISSUE TITLE
All donation buttons disabled if donation is over balance

### ISSUE THREAD

**Issue by milansmolik-dragon** [vacuumlabs/adalite#521]
**Expected behavior**

1. I write transaction amount close to my balance
2. I choose default donation (40ADA atm.), which would put the transaction over my balance
3. I am correctly informed that I don't have enough balance
4. I can then either uncheck the donation or choose smaller donation amount, then execute the transaction

**Actual behavior**

4. I can't choose lower donation until I lower the Amount to send. I can't even uncheck the default donation, effectively locking me until I lower the amount.

![donation](https://user-images.githubusercontent.com/50991346/66118578-079d7600-e5d7-11e9-8fae-4eb81d727c09.png)

**Comment by xdzurman** [comment]
Fixed in commit 2d4e0bc - Add unaffordable state of donation button
