### ISSUE TITLE
"New bridge available"

### ISSUE THREAD

**Issue by sedwardstx** [vacuumlabs/adalite#528]
When connecting to my Cardano wallet using Tezor model T from adalite.io I get a message from https://connect.trezor.io/7/popup.html which says "New bridge is available", and button that just redirects back to wallet.trezor.io.  This site does not have any link I can see to update to a new Bridge.  My Model T wallet has latest firmware already.  How to update to the new bridge?

**Comment by refi93** [comment]
fixed in #606
