### ISSUE TITLE
Important change in Cardano wallets derivation paths for the Incentivized TestNet / Shelley

### ISSUE THREAD

**Issue by KtorZ** [vacuumlabs/adalite#540]
Hello :) 

You guys may be interested by this change: https://github.com/input-output-hk/cardano-wallet/pull/1081
I've heard you were working on having something working with the incentivized testnet so it'd be nice to keep adalite somewhat compatible with Yoroi and Daedalus.

Cheers.

**Comment by PeterBenc** [comment]
Closing since the issue is outdated.
