### ISSUE TITLE
Adalite Chrome connection to Ledger Nano X fails most of the time

### ISSUE THREAD

**Issue by jonstaffnerd** [vacuumlabs/adalite#590]
On a high speed USB 3.0 hub, Adalite fails to recognize that the Ledger Nano X is opened with ADA app loaded and continues to ask that I touch the Nano X. If I switch to another USB 3.0 high speed slot that is through a combined ethernet/display/USB 3 hub, I can get the connection to work some of the time. 

Clearly there is some kind of timing issue/handling issue with Adalite. I am on current versions for Windows 10, Nano X, etc. I have seen issues about this from summer 2019 about switching to a different tunnel but don't know the status of that.

**Comment by jonstaffnerd** [comment]
Ok figured out the correct sequencing. The Ledger Nano X has to be open with Cardano ADA app already showing "Waiting for commands" when the browser-based AdaLite is initiated. Then it properly recognizes the Ledger, let's you respond to Address messages on Ledger (2 of them), then reads the balances from the Ledger. Any other sequence like opening AdaLite first, then loading app on Ledger, then trying to sync does not work.

**Comment by MichalPetro** [comment]
Thanks for resolving this by yourself @jonstaffnerd , much appreciated :)
