### ISSUE TITLE
Ledger X connection failed to the wallet

### ISSUE THREAD

**Issue by ferncastro** [vacuumlabs/adalite#593]
Hi,
I am trying to connect with my Ledger X and I've got this message now. 

NetworkError: nection failed. Please check your network connection.

I can't log in to my wallet.

I've tried chrome, brave and other computers and always the same message.

Please, can you help me,
Thanks,

**Comment by refi93** [comment]
Hi @ferncastro, we are sorry - there was an outage of our Cardano nodes at that time, i.e. the whole wallet was not working and failing with a "NetworkError". We restored the nodes around 23:20 UTC, therefore you should not be experiencing this issue with your Ledger anymore
