### ISSUE TITLE
Parse shelley transactions to extract values for tracking

### ISSUE THREAD

**Issue by xdzurman** [vacuumlabs/adalite#622]
Shelley transactions parsing on submit has been disabled by https://github.com/vacuumlabs/adalite/pull/620 since it was not working and causing memory leaks in prod due to some nested failure.

This issue is about restoring shelley transaction parsing in order to have statistics again.

**Comment by PeterBenc** [comment]
This issue is a bit outdated, but it regained its meaning in a sense, that we could add delegation and withdrawal tracking.
