### ISSUE TITLE
Merge NodeOutOfSync and ServerError on testnet

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#628]
Backlog issue stemming from #615 

NodeOutOfSync and ServerError seem to reflect the same kind of problem (if the nodes are out of sync, they are effectively down), therefore I suggest merging them into a single "ServerError" exception.

Link to code translating those errors to text for context:
https://github.com/vacuumlabs/adalite/blob/a180d0096d19b6a6913c381e92cda08fb21d038d/app/frontend/translations.ts#L55

**Comment by PeterBenc** [comment]
Closing this since the issue is already resolved.
