### ISSUE TITLE
Simplify stakepool listing in frontend state into a single property

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#629]
Backlog issue stemming from #615 

Currently, we have a separate key in state for valid stake pools and ticker to Id mapping. This could be simplified to have a single array of stake pools that would have selectors implemented on top of it. The benefit is that it is more flexible in terms of introducing new access patterns and keeps a single source of truth which decreases the likelihood of future bugs. It also prevents issues in case of a stake pool being named like a prototype property of object, like "constructor"

Link to code for context:
https://github.com/vacuumlabs/adalite/blob/a180d0096d19b6a6913c381e92cda08fb21d038d/app/frontend/wallet/shelley-wallet.ts#L201

**Comment by PeterBenc** [comment]
Should be already resolved in the mentioned issue.
