### ISSUE TITLE
Fix testnet branch to support Byron

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#631]
We would like to have both byron and shelley on the same branch which would simplify deployments and alignment of features while both Byron and Shelley is in use.

As of now, the testnet branch in theory supports Byron (the flag `ADALITE_CARDANO_VERSION` is there), but it was not tested and it may be unstable if runnable at all.

Before promoting the testnet branch as the new master, we should make sure that at least the following works:

- [x] log in with a 12, 15, 27 word mnemonic works (see tests for reference mnemonics)
- [x] login with the wallet secret exported to a JSON
- [x] Ledger login works as expected
- [x] Trezor login works as expected
- [x] Sending transactions works
- [x] Verifying address for hw wallet (Ledger/Trezor) works
- [x] After switching to "Shelley" mode, everyting still works as expected

We should also make sure to port the changes that meanwhile appeared in master: https://github.com/vacuumlabs/adalite/commits/master (commits since 48514e0ba01f94410da0f51229d075e196ebd6ca)

Usage of adalite with hw wallets is documented here:https://github.com/vacuumlabs/adalite/wiki/How-to-use-Ledger-Nano-S-and-Nano-X-with-AdaLite

**Comment by elfinka** [comment]
Done
