### ISSUE TITLE
Donate should not be disabled when people Send and use Max amount.

### ISSUE THREAD

**Issue by loupiote** [vacuumlabs/adalite#653]
Donate should not be disabled when people Send and use Max amount.

Instead, the donated should be be substracted from the Sent amount.  Maybe to make sure people don't get confused, display the amount that will be received, i.e. Sent amount minus fees, minus donation.

**Comment by MichalPetro** [comment]
This may cause confusion, currently, I dont know what would be a good UI for this. Thanks for suggestion but we will probably pass on this feature.
