### ISSUE TITLE
Invalid address when sending to Shelley Mainnet wallet

### ISSUE THREAD

**Issue by CaptainCrackers** [vacuumlabs/adalite#661]
I'm unable to send my ADA to the new Daedalus wallet running on the Shelley mainnet.  I get an "invalid address"  and I'm guessing this is because the new mainnet has different wallet address structures.  How can I send from my hardware wallet to Daedalus shelley mainnet?

**Comment by juliustayl** [comment]
According to their twitter account (@AdaLiteWallet) they are planning to release an AdaLite Shelley version tomorrow.....so maybe the issue will be fixed then.

https://twitter.com/AdaLiteWallet/status/1288654132606312449

**Comment by MichalPetro** [comment]
@CaptainCrackers also you will need to wait for Ledger and Trezor to update their firmware. Ledger is in progress, Trezor should happen on 5th of August.

**Comment by PeterBenc** [comment]
Closing this since the integrations for ledger and trezor are already fully functional.
