### ISSUE TITLE
develop-shelley: duplicated code?

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite#664]
I noticed some code duplication:

https://github.com/vacuumlabs/adalite/blob/develop-shelley/app/frontend/wallet/shelley/build-transaction.ts#L46
https://github.com/vacuumlabs/adalite/blob/develop-shelley/app/frontend/wallet/shelley/shelley-transaction-planner.ts#124

Are both used?

**Comment by PeterBenc** [comment]
Closing this as issue #682 addresses this.
