### ISSUE TITLE
Not really an issue: feature request for FAQ file to indicate time wallets can send and receive after Shelly update

### ISSUE THREAD

**Issue by WintelRob** [vacuumlabs/adalite#666]
I noticed on the FAQ file no indication to end-users when you thought that the wallet would be able to send or receive ADA. As of this moment, all wallets seem locked. (I personally cannot move ADA from any wallet or exchange.) 

It would be nice to have a rough estimate of the time frame for send/receive availability after this fork/update.

Thanks for the nice work!

**Comment by MichalPetro** [comment]
Hi Rob, mnemonic wallets and Ledger wallets should work, Trezor should work on 5th of August. Please describe issues you are having.

**Comment by PeterBenc** [comment]
Not an issue so closing.
