### ISSUE TITLE
Remove automatic export of Byron public key for HW wallets

### ISSUE THREAD

**Issue by MichalPetro** [vacuumlabs/adalite#670]
Currently, HW wallets need to export 2 account public keys in order to load both Byron addresses and Shelley addresses balances. We need to make the Byron public key optional for users not to bother users that already transferred funds to Shelley addresses.

I would like to add a checkbox "Load legacy Byron wallet balance"  to the HW wallets login screen (with some explanation). The checkbox will be by default checked for 1-2 months and we will uncheck it after.

**Comment by PeterBenc** [comment]
Just an idea, so I don't forget, maybe after those 1-2 months, we shouldn't just disable the checkbox, we could remember users choice the same way we remember if the user closed the staking banner. So some users might have the checkbox checked by default and others won't.

Another thing to mention is non-staking balance. Exchanges and wallets including us support sending funds to legacy addresses. Users who had the checkbox unchecked and received funds on these addresses would never realize it. They wouldn't see it in balance nor the transaction history. A possible solution would be to add a button that would reload balance and tx history including legacy addresses as well.

**Comment by PeterBenc** [comment]
Implementing bulk export of public keys solved this issue so closing this.
