### ISSUE TITLE
Ability to remove staking delegation

### ISSUE THREAD

**Issue by colbybridges** [vacuumlabs/adalite#675]
Only able to stake and change staking delegation. There is no ability to remove staking delegation and not be staking.

**Comment by MichalPetro** [comment]
Yes, this feature was not implemented yet, why do you need it? Workaround is creating new wallet withhout staking delegation and move all funds there.

**Comment by colbybridges** [comment]
Ok,

No worries. I just wanted to stake to a particular pool & I put it in the wrong ticker. When I tried to just not stake to anything, I couldn't. I ended up just moving staking to the ADA lite pool.

________________________________

**Comment by roccomuso** [comment]
Will you introduce this unstaking feature? :+1:

**Comment by MichalPetro** [comment]
It is impossible to "unstake", you can only re-delegate or de-register the staking key. Yes, we plan to introduce the de-registration of staking key but we don't think it is necessary in the short-term.

**Comment by Zinitus** [comment]
If I just de-register my staking key will my funds be available for transfer?
Any danger of losing anything by de-registering?
