### ISSUE TITLE
Nemonic wallet not displaying recent Tx -> disabling ITN redemption

### ISSUE THREAD

**Issue by Power2theEdge** [vacuumlabs/adalite#683]
This transaction is not reflecting in my ADA balance, after 56 confirmations, which is preventing me from redeeming ITN rewards. https://explorer.cardano.org/en/transaction?id=9dd5db35ed521b01a232d08b165f18b3551864d911b7973a1aadd5489e3a6a0d

**Comment by PeterBenc** [comment]
Hi @Power2theEdge, is this still an issue? I guess what you are trying to do is to send some funds to a wallet on which you have some rewards from ITN am I right? Are you sure the address you are sending belongs to the wallet with your ITN rewards?

**Comment by Power2theEdge** [comment]
Yes the problem still exists and you are correct on sending enough ADA to fund the ITN rewards redemption. I have triple checked the address. I chose the first address on the list from the sending page of the wallet that contains my ITN rewards

**Comment by MichalPetro** [comment]
Can you please post a screenshot of your balance on Staking screen? Also can you please take a screenshot of your addresses? Feel free to send to our email address adalite at vacuumlabs dot com and refer this issue.

**Comment by Power2theEdge** [comment]
It appears I just needed to allow more time for the transaction to be completed. The transfer was accurately reflected in my wallet and my ITN rewards have successfully been redeemed. You can close this case. Thanks for the amazing support.
