### ISSUE TITLE
blockchain explorer in .env.example is down

### ISSUE THREAD

**Issue by enolan** [vacuumlabs/adalite#685]
When running the wallet from a git checkout the app attempts to connect to http://ec2-34-243-74-88.eu-west-1.compute.amazonaws.com:3333 and times out.

**Comment by PeterBenc** [comment]
Hi @enolan, the .env.example file was not updated during the development of shelley. I will update the example file soon. Sorry for inconvenience.

**Comment by PeterBenc** [comment]
https://explorer2.adalite.io is the "new" backend url. I will push updated .env.example soon but this should for you until then.

**Comment by PeterBenc** [comment]
closing this since the issues is already resolved. .env.example file is updated.
