### ISSUE TITLE
Invalid address while using exchange

### ISSUE THREAD

**Issue by Kani999** [vacuumlabs/adalite#690]
Hello,

I'm running into the issue with an invalid ADA address when I'm trying to exchange other cryptos to my ADA.

Maybe it's in the old format, I create an account before a fork. But I don't see any option on how to create a new address in a proper format. I did not found any FAQ topic either.

Thanks

**Comment by PeterBenc** [comment]
Hi, I guess what you are trying to do is to send funds from an exchange to a wallet created on Adalite am I right? The old addresses have the format starting with `D...`. or `A...` and the new format starts with `addr`. To which of these types do you have trouble sending your funds? And from where?

**Comment by MichalPetro** [comment]
I checked this, Kani is probably referring to our exchange partner on exchange.adalite.io. They have some issues using the new address format, I am working on the issue with them.

Thank you @Kani999 for reporting this

**Comment by Kani999** [comment]
@MichalPetro Yes, that's is exactly what I meant. 

@PeterBenc I thought that `addr` is the old format. If its the new one, everything is ok for me, as the @MichalPetro is working with `exchange.adalite.io` on a fix. 

Thanks for clarifying.
