### ISSUE TITLE
Receive address

### ISSUE THREAD

**Issue by Laura2348** [vacuumlabs/adalite#691]
I am very new to this.. when signed in and trying to purchase another crypto from other site.. in the ada site I dont have a receiving address.. only a delegate stake address, or I can send.. but no receiving, which when I put that on the other site its says invalid.. Help..

**Comment by MichalPetro** [comment]
Hello,

your addresses are on Send screen under My Addresses tab.

**Comment by Laura2348** [comment]
What about receiving? as I am trying to purchase crytpo from another site that doesnt support Nano X, so when i link it all together and open the ada lite page there is no receiving address on where to send it to if that makes sense? @MichalPetro  thanks for replying this is driving me nuts on trying to figure it out

**Comment by MichalPetro** [comment]
@Laura2348 The above "My Addresses" tab are your addresses to receive funds. We probably have to rename the screen to Send & Receive...

**Comment by Laura2348** [comment]
@MichalPetro I think I get you..  so the adalit is like a middleman to help the transaction through to the nano X from the supplier.. so hopefully you can help me on this.. if i want to purchase cardano.. but cant make an "account" on the nano x , can it be sent to another account/address..like ETH or Bitcoin..? sorry to bombard you i just dont know how to do this..

**Comment by MichalPetro** [comment]
Hello Laura,
I strongly suggest that you do some research on your own about how cryptocurrencies, wallets and Ledger work before doing any material crypto purchases/transactions. Also, I strongly recommend that you try any transactions with pennies first to make sure you understand what you are doing.

AdaLite acts as an interface to interact with your Ledger wallet. When you access your Ledger using AdaLite you will see My Addresses tab on the Send screen. These are addresses for your Cardano Ledger wallet. When you purchase any ADA, you should send it here.

Please refer to this guide on how to work with Ledger on AdaLite. This Guide is not totally up to date and it is for Nano S but it should give you a general idea of how it works. https://github.com/vacuumlabs/adalite/wiki/How-to-use-Ledger-Nano-S-and-Nano-X-with-AdaLite

**Comment by Hussain73** [comment]
Hi,
I am new to this ADAlite.  I tried to transfer my ADA coins from NDAX account to my NANO X through ADALite.  I copied the address from the receive tap and plugged it into NDAX and the coin has been withdrawn from NDAX.  But I don't see the ADA balance in ADALite?
