### ISSUE TITLE
Cannot Log into ADA Lite via Nano Ledger S

### ISSUE THREAD

**Issue by Gbutler123** [vacuumlabs/adalite#698]
I get the following error when try to access access my ADA on my Ledger through ADA LITE:

TransportStatusError: Ledger device: Action rejected by Ledger's security policy. Please make sure that the Cardano Ledger App is opened before initiating the connection.

The app is open.

**Comment by MichalPetro** [comment]
Hello,

please update you Cardano Ledge app, instructions how to do that are here: https://support.ledger.com/hc/en-us/articles/360006523674-Install-uninstall-and-update-apps
