### ISSUE TITLE
12 words mnemonic and shelley addresses

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite#713]
I'm wondering if that's accurate: 

![image](https://user-images.githubusercontent.com/6730217/91838856-6daed500-ec4e-11ea-87ed-90f7c42424ea.png)

With the 12 words you can generate a 32 bytes privateKey seed and from that a 64 bytes xpub to encode shelley address.

**Comment by PeterBenc** [comment]
Well, you are right, 12-word mnemonics could be in theory used with Shelley features, but we wanted to stop supporting them for a couple of reasons. Btw also Daedalus is telling its users to migrate to 24-word mnemonics and there is this whole confusion with hierarchical deterministic and non-deterministic address derivation so it makes sense for us to rather have users migrate to 15-word mnemonics.
