### ISSUE TITLE
ADLT pool only has one relay.

### ISSUE THREAD

**Issue by billbazza** [vacuumlabs/adalite#717]
I've delegated to ADLT pool as I really like the ADAlite.io and I want to support the devs, but I am worried that there is no redundancy built in to the relay nodes and so is at risk of downtime if there are issues or upgrades.

Am I mistaken, or does pooltool not show the correct relay data?

Cheers
W

**Comment by xdzurman** [comment]
At registration time of the pool, you need to specify at least one relay. We have three pools, each has a unique relay node registered with it and we have another relay node not directly registered by any pool. Therefore, we have four relay nodes, all connected with each other and with all three pools. We are also closely connected with EMURGO relays so no worries about downtimes :)

**Comment by billbazza** [comment]
Thank you for confirming, I thought there would be a good explanation.
