### ISSUE TITLE
Cannot connect my Ledger Nano X

### ISSUE THREAD

**Issue by Nettowarrior** [vacuumlabs/adalite#721]
I cannot connect my Ledger Nano X to AdaLite, it is stuck on the Windows security popup where my Ledger Device is "Waiting for commands".  I can connect to Ledger Live and XRPToolkit without any issues.  I raised a support ticket with Ledger and they have confirmed that the issue is related to AdaLite.

My OS Version is Windows 10 (2004)
I have having this issue on all browsers listed below:
Brave (1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit))
Firefox (78.0.2 (64-bit))

**Comment by MichalPetro** [comment]
Hello,

What helped all people with your issue is to use the Connect with WebUSB button just under the pink Unlock with Ledger button. Feel free to reach out if your issue persist after you tried this.

Best,
Michal

**Comment by Nettowarrior** [comment]
Hi,

Web USB worked for me thank you

Kind Regards
Mohammed Anshar Ali

**Comment by kmm123123** [comment]
hello to you all, im no pc geek so please help me... my ledger will not connect to my desktop adalie site. it has worked once before but now it wont. i Remember seeing a windows link download on this github that seemed to fix it last time i believe, can anyone send me that lnk or advise me more? kindest regards kate x

**Comment by MichalPetro** [comment]
@kmm123123 Hello Kate, can you please describe the behaviour? Do you get any error message? Are you using Windows and Chrome browser?

**Comment by MichalPetro** [comment]
Possible solution: use Connect with WebUSB button just under the Unlock with Ledger button.

If it doesn't work, try to execute steps displayed here and try Connect with WebUSB again: https://shapeshift.zendesk.com/hc/en-us/articles/360011307520-Replacing-Your-Driver-Using-Zadig

(NOTE: Do not run random .exe files recommended by people on Internet unless you understand what you are doing. The above guide is from ShapeShift which is a reputable crypto management platform and it shows how to replace your USB drivers)
