### ISSUE TITLE
Once Again, ADALite Not Releasing Rewards ...

### ISSUE THREAD

**Issue by rehctelf** [vacuumlabs/adalite#726]
Now, attempts to withdraw ADA rewards on ADALite results in the following error: "Transaction Error. Insufficient funds for the transaction. Your balance is NaN ADA." I left 100 ADA in that wallet to cover transaction fees. What is "NaN ADA" and how do I fix it?

**Comment by PeterBenc** [comment]
@rehctelf Hi, sorry for the inconvenience, we've already fixed the bug, so please try now and let us know.
