### ISSUE TITLE
U2F DEVICE_INELIGIBLE

### ISSUE THREAD

**Issue by Gruchalski** [vacuumlabs/adalite#733]
Hello,

I am getting the following error when connecting my Nano Ledger s.  I updated the firmware on the Nano Ledger and it is still doing the same thing.   There is no updated on the Ledger to do a Cardono update and Adalite is my Cardano Wallet. I am not sure what to do here.   Thank you for your help.

TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE.If you are using a hardware wallet, please make sure you are u sing the latest version of the Cardano application.

**Comment by Gruchalski** [comment]
I used my Recovery Seed to gain access and then this is showing up.   I am now really concerned about my Cardano funds.   

You are accessing Shelley incompatible wallet.
PROCEED WITH CAUTION
You are accessing a wallet with 12-word mnemonic passphrase. These are not longer supported thus you won't be able to use the Shelley features. Depending on which wallet did you use before, we may not even show your whole balance (this applies especially for Daedalus wallet users) so if you dont see your whole balance, please use Deadealus. We strongly advise you to immediately transfer all funds from this wallet to a new Shelley compatible wallet.
We don't guarantee that the balance we show is correct!
To use your wallet to full extend please follow this guide to converting your wallet to AdaLite Shelley-compatible wallet.
1.	If you participated in the Incentivized Test Net staking, withdraw your rewards to your wallet balance on the "Staking" tab (top left corner of the screen), clicking on the Withdraw Rewards button (this button is visible only if you have some ITN rewards).
2.	Logout of this wallet.
3.	Navigate to main page and click "Create New Wallet" in the right top corner.
4.	Wrote down your new 15 word mnemonic seed phrase.
5.	Login with the new 15 word mnemonic.
6.	Navigate to the "Sending" screen and make copy of any of your address shown in "My Addresses tab"
7.	Now, login to your old (12-word mnemonic wallet) and send all your funds to the address you copied from the new wallet. Please make sure this address is starting with "addr1"
8.	Use the new 15 words mnemonic phrase seed wallet from now on with all the Shelley features.

**Comment by MichalPetro** [comment]
Hello @Gruchalski ,

First of all - never ever enter your Ledger seed anywhere on the internet. It will not work anyways (the purpose of the seed is to restore the wallet on Ledger in case the device is reset or damaged. 

Regarding your U2F DEVICE_INELIGIBLE issue - this is a common issue on Windows and there are several possible reasons/solutions.

First I would recommend trying to connect your Ledger using Connect with WebUSB button just under the Unlock with Ledger button.

If it doesnt work just use the Unlock with Ledger button. Please note, if any grey pop-up windows pops up, DONT CLOSE IT.  Ignore it and pay attention to what your LEdger screen is showing.

Let me know if any of the above helped.

**Comment by Gruchalski** [comment]
Thank you for your reply and the advice.  I will not do that any more.   I have tried to use the WebUSB and the Ledger Hardware and both give me the same error.  On the edger it tells me to export private key and I follow the instructions and it still results in the same error.

**Comment by Gruchalski** [comment]
I got in.   AS you stated, I did not entirely follow the directions on the ledger.   Thank you for your help!
