### ISSUE TITLE
Reduce number of prompts when loading Trezor wallet

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#734]
Currently Adalite triggers two prompts when loading the wallet from Trezor. This is because Adalite asks separately for the shelley root public key and for the byron one.

The interaction can be reduced to a single prompt by refactoring the wallet import to use the bulk public key export feature of the trezor connect api, as outlined here: https://github.com/trezor/connect/issues/679

Note: this is an issue for Ledger as well, but there currently isn't a way to export public keys in bulk, so it's not possible to fix it if we want to preserve the UX of having both Shelley and Byron addresses at the same time.

**Comment by PeterBenc** [comment]
We are already supporting bulk export of public keys so closing this.
