### ISSUE TITLE
Unable to use ADALite with Wallets - Servers Down

### ISSUE THREAD

**Issue by ShenmueGuy** [vacuumlabs/adalite#746]
Please fix this immediately as I have funds and need to make some transactions

The message I get when using Trezor or Ledger is this

ServerError: Our servers are probably down. Please try again later and if the problem persists, contact us.

**Comment by MichalPetro** [comment]
Hello, this was already fixed some 12 hours ago. Sorry for inconveniences

**Comment by ShenmueGuy** [comment]
Thank you so much
