### ISSUE TITLE
funds missing

### ISSUE THREAD

**Issue by sheikyormunny** [vacuumlabs/adalite#750]
hi guys apologies if im in the wrong place, i opened an account on adalite with my ledger nano x wallet, successfully transfeerred my cardo funs over, all showing in account cool, then i went to stake it , using the delegate button on the right, and now all my funds have gone to the staking address i think and none showing in my account ? ....help !! , have i been victim of a scam ? or does it take time to kick in, ?, i see the wallet i sent my funds to in transactions ...... what does one do ?

**Comment by PeterBenc** [comment]
Hi, please can you make sure you were visiting **adalite.IO** and not some other site?

**Comment by MichalPetro** [comment]
Also please send us the transaction ID to adalite (@t) vacuumlabs (dot) com

**Comment by sheikyormunny** [comment]
hi guys thanks for this, ok so the process i done was as follows brought my cardo over to adalite wallet , all showing well, and yes it was adalite io, address , i succesfully placed my funds over, sent one test small amount followed by the rest , so all was in my staking balance showing up ok , so on the right hand side of the staking screen i pressed delegate , and thought id sent funds to the staking pool, but afterwards the transaction went through and nothing on my screen confirming any staking funds and history ?? , enclosed 4 screenshots of my account and the transactions ....  where did i go wrong ? and have i lost the lot, the address i sent to seems to have it still there and thats the only balance in the wallet ?


Michael Mc Donald

UK Mobile: 0044(0)7821 676295

________________________________

**Comment by sheikyormunny** [comment]
have sent screenshots to the mentioned address via the email ......

**Comment by sheikyormunny** [comment]
any joy guys or any other info needed ?

**Comment by MichalPetro** [comment]
Hello,

after reviewing the transaction you posted it seems like there is no delegation certificate in it. Either you created a standard transfer funds transaction or you have been tricked by some malicious web page to do a transaction to scammers address instead of a delegation transaction.

Last known similar scam was on address adalite . org (please note, although the site seems identical to ours, it is a scam website that will trick you to send funds to scammers. I recommend that you review your browser history to check if you visited this site or any other adalite domain with tld different than .io (which is the only true adalite website)

**Comment by noa969** [comment]
I have the same problem my adress Ae2tdPwUPEZ7arRHMtRNXokpJBv3DNzLDnzfoFyVipTTo8LmAogcdwtd4he
 TX 17ef93a9232f6fac74b03d070b8567bf5426f6f7aa035282b59425d3b7333406

**Comment by refi93** [comment]
Hi @noa969 can you please clarify whether you were logging into Adalite via a mnemonic, Trezor, or Ledger? Were you ocnverting your funds to stakable in the staking interface or making an ordinary transaction? i.e. where did you get the `addr1qydnr6kckjz7av3wh00upqaz7ajcd0h48dzszweg4dvvmmeutzz65puqyhj67rqzymsch2ntc3hex6w2u4mhym8p5p5qxpnhsv` address from?

Does tIf you were making an automatic conversion to stakable funds in the staking interface, can you check whether the topmost address in the list of your addresses is `addr1qydnr6kckjz7av3wh00upqaz7ajcd0h48dzszweg4dvvmmeutzz65puqyhj67rqzymsch2ntc3hex6w2u4mhym8p5p5qxpnhsv` (the one that received the funds) or is it something different?

Can you also please verify in your browser history whether you were actually visiting adalite.io and not other similarly named site (ada-lite  .io / adalite   .org / etc.)?

**Comment by noa969** [comment]
Good morning. And thank you for fast answer.
I was on the scam side ada-lite.io. I have make the transaction withe ledger nano x and lost all my ada. Are my rest Pfunds save? Like bitcoin ether and many more.... 
Can I get my Pfunds back? 
What I must do 

Patrick Haas

**Comment by refi93** [comment]
Hi @noa969, sad to hear that :( unfortunately, there's no way to get the funds back once they were sent to an address that you don't have control over. Next time, when sending funds to an address you think should be yours, you can verify this via the "verify on Ledger" functionality as described here: https://github.com/vacuumlabs/adalite/wiki/How-to-use-Ledger-Nano-S-and-Nano-X-with-AdaLite#verify-the-receive-address-on-your-ledger-nano-s-with-adalite, ensuring you don't unknowingly send funds to a (malicious) 3rd party. 

Given that you are using a hardware wallet, the remaining funds, whether in ADA or other currencies, are safe and cannot be stolen as long as you don't confirm such a transaction.

**Comment by sheikyormunny** [comment]
after reviewing everything , and rebooting and cleaning all pcs with clean installs (what fun that was 2 days later i think ive got all codes for authentication sorted now), i guess i got scammed on the other adalite site , im just not sure how,  when i was in my account and the funds went missing from the staking process .... when sent from there , all gone !! , wow , this has put me off ada to be honest with the ease it was done, from the official site , i can see my funds went there , but im certain it was in the staking process my funds went to a wrong address ?

**Comment by refi93** [comment]
adalite.io is the legitimate site but there are elaborate scam sites that look exactly the same, except the URL. ADA is no special in that way and similar scams exist for other crypto web wallets, like myetherwallet.com and the overall attack vector is inherent to all websites on the internet, like internet banking websites. Visitors need to make sure they are visiting the trusted website and not some even slightly misspelled/altered version of it. Bookmarking the trusted web wallet and making sure you are always accessing it via the bookmark is helpful in that regard. An alternative approach would be using browser addons instead like Yoroi for ADA or Metamask for ETH, but you still need to make sure that you are downloading the actual addon and not some scam version of it.

Regarding staking, a common scamming scheme is that the scam site makes you believe you are signing a delegation transaction, but you are actually signing a standard spending transaction depositing to the scammer's address. If you are logged in via a hardware wallet, it displays clearly that it's a standard spending transaction that sends X ADA to address Y but despite of that is easy to get misled by the scam site's claims - again, a common problem across all cryptocurrencies, not just ADA, and the only effective protection is to understand and carefully read what the user is signing and react accordingly.

**Comment by noa969** [comment]
Good that my rest Pfunds are save. I collect for the future of my daughter. I make it between 2016. That is my first scam and all my ada 2000 is stolen. I need a way to get 2000 ada.... can i make promotion for the right side? I have 632 crypto follower on twitter.... ohh no my ada ....

**Comment by sheikyormunny** [comment]
i really think you guys need to do an updated idiots guide to using the ada and staking it, im not going anywhere near it as it is now, as scammers are obviously linked into this, i am pretty computer savvy , had all my ada to the official site as is documented, and the funds went missing when i staked, not before , it was sitting in the account ok , till the staking so somehow i went out of the site , while the staking process happened.... as i say if it was a one off i can understand , but there is lots of people piling in here all been robbed the same way ..... so it is worrying me to the point i wont go near ada io , at all ... you lot can dress it up all you like , and say i went to a rogue site etc, but i got to the rogue site from inside ada  !

**Comment by sheikyormunny** [comment]
there is obviously something very wrong here with the amount of people losing their funds ... and pc literate people at that....

**Comment by MichalPetro** [comment]
@sheikyormunny you got to the rogue site from spam fake Coindesk email promising huge staking returns (first warning sign) that transferred you to fake Cardano Foundation site (https://cardanofoundaton.org/) promising high returns if you re-delegate quickly (another warning sign), that finally transferred you to AdaLite fake website (ada-lite.io or adalite.org). 

So you may be in perception that you came from official ADA site but actually, it was fake too.

**Comment by sheikyormunny** [comment]
thats part of what im saying , its too easy to get done over .... if scammers have infiltrated and got all angles covered

so your saying my funds where never even moved into the official ada ?, thats even more worrying, and confusing , as i made the transaction into ada, and then from there, to the scammers address... ???? so why would they get me to move it twice ?, why not straight to scammers ? //// confused dot com....



________________________________

**Comment by refi93** [comment]
@sheikyormunny Adalite is merely an interface to your wallet's addresses on the blockchain and it lets you perform operations such as spending/staking with them if you pair your hardware wallet with it or insert the mnemonic, if that's your method of access. The funds do not "reside" on any infrastructure of ours, they are directly on the Cardano blockchain and you can access them from any other Cardano wallet based on the same cryptographic standards, such as Yoroi or Daedalus

What the scammers did is, they set up a malicious adalite-like interface on a similarly looking URL. That malicious interface would let the user connect to their hardware wallet and operate with their funds (which they still legitimately hold at that point) but the scammers also internally altered the operations they offer to redirect the funds to an address they have control over. So the funds actually went "straight" to the scammers in a sense. The funds originally resided on one of the user's addresses but the scammers would not have access to them without the user giving consent to sign a spending transaction initiated from the malicious interface on their hardware wallet.

The paragraph above applies if you are using a hardware wallet. Using a mnemonic is inherently unsafe and your only line of protection against scam websites is making really sure you are interacting with the right website as once a malicious website gets hold of your mnemonic, the scammers can directly withdraw the funds by deriving the corresponding private keys.

Hope that clarifies your doubts. We are already taking steps to have the scam sites taken down and working on a blog to raise awareness about adalite-like scam sites with advice on how to avoid getting scammed. At the same time, following [general advice](https://www.phishing.org/10-ways-to-avoid-phishing-scams) to avoid getting phished and general hardware-wallet [best practices](https://medium.com/ledger-on-security-and-blockchain/ledger-101-part-3-best-practices-when-using-a-hardware-wallet-198b60df2681) is already good enough to stay safe.

@noa969 we are sorry but we do not offer any similar arrangement

**Comment by sheikyormunny** [comment]
thanks for that , yes i think definitely more awareness needed,  i see you guys seem to be getting on top of that now i see the warnings on the real site, but for me lesson learnt ..the hard way .... is there any other way to learn ?... i do appreciate your time , and your responses, all good to leave here and forewarn others....

**Comment by refi93** [comment]
You're welcome, as a starting point to learn more about Adalite/hw wallets/staking I can recommend our wiki: https://github.com/vacuumlabs/adalite/wiki and here's a guide from MyEtherwallet on how to avoid phishing: https://kb.myetherwallet.com/en/security-and-privacy/pro-tips-how-to-avoid-phishing-scams/ which is applicable for other web wallets and cryptocurrencies as well. Also, here's our blog: https://medium.com/@adalite

**Comment by Jon1325** [comment]
I was left in shock and depression after being deceived by bitfinex investment where I lost about 395,000 USDT of my entire life savings which I was planning to get a company after my retirement as life investment for my kids but this nitwits stole it from me. However after weeks of my depression I finally met REMOTESPYTECH (at) gmailc0m through a close friend referral and he got back all my stolen assets instantly without hassle or hidden fees. He’s the only real deal out here as I’ve tried many but they failed. He was my final and last hope. I’m grateful Mr Romero delivered. Get in touch with him now!!!!

Email: REMOTESPYTECH@GMAIL.COM

whatsapp: +1 (352) 870-0844

Real Deal 

Reliable tech team
