### ISSUE TITLE
 a suggestion to add the feature of importing addresses and private keys as accounts

### ISSUE THREAD

**Issue by zoowii** [vacuumlabs/adalite#756]
This is a suggestion to add the feature of importing addresses and private keys as accounts instead of only importing by mnemonics.

Reason: Cardano wallet has been revised many times, and there are many address formats, but other wallets do not support directly importing the private key (xpriv+xpub+chaincode) of the Byron stage and using the balance in the Byron address

**Comment by MichalPetro** [comment]
Hello @zoowii , this is something that we wont most likely do. We don't see a use case for it and this can be done by powerusers using cardano-cli tool.

It will be possible to use HW wallets for pledge soon and this should eliminate the need for this feature for common users.
