### ISSUE TITLE
AdaLite automatic transfer from Byron to Shelley lost my ADA??

### ISSUE THREAD

**Issue by greyman72** [vacuumlabs/adalite#757]
Hello, I'm sincerely hoping you can help me untangle what might've happened to my ADA. I logged into my AdaLite wallet with my Nano X as usual (yes, I confirmed I was at adalite.io) and all of my ADA was there as expected. I'd heard I needed to migrate over to a Shelley address and that AdaLite had an automatic way to do it. So I went to the Staking interface and clicked the button to convert it... Now my wallet shows zero ADA and I'm not sure what to do.

Here's the transaction hash:
1398090c1bf7c6cfb7d5b3500e7b057c72be8aedfddffc9b6b0d5a2fd72bc7ba

Thank you SO much, in advance. Any help you can provide is TREMENDOUSLY appreciated.

**Comment by refi93** [comment]
@greyman72 can you verify whether the address `addr1q84anmv04t86cxfxfz2msfyr2mlszfkeznr9rarc9w7vz0s0mlf98dq0vcyxnlhh4ygjmz7044quwja90g5fnrlxsp5qv2prqm` (the one that received the funds) appears among addresses in Adalite's interface once you log into it with your Ledger device? It should be the topmost address on the list of addresses, if it's actually yours.

Also, do you have a passphrase set on your Ledger device (https://support.ledger.com/hc/en-us/articles/115005214529-Advanced-passphrase-security)? If so, can you make sure you are inserting the right passphrase?

Also, you say that you made sure you were visiting adalite.io . Indeed, we came across a scam site with the URL `ada-lite   .io` (".io" spaced out intentionally to not promote it) - wasn't by any chance the site you visited that one? Can you check in your browser history?

**Comment by greyman72** [comment]
It looks like it's all my fault and I got scammed. I checked my browser history and it was https://ada-lite.io

**Comment by refi93** [comment]
sad to hear that :( we already reported the site so it's picked up by scam-site detection tools
