### ISSUE TITLE
this is whats showing

### ISSUE THREAD

**Issue by ron958** [vacuumlabs/adalite#763]
{"exception":{"values":[{"type":"NetworkError","value":"POST https://explorer2.adalite.io/api/bulk/addresses/summary has failed with the following error: TypeError: Origin https://adalite.io is not allowed by Access-Control-Allow-Origin.","stacktrace":{"frames":[{"filename":"[native code]","function":"promiseReactionJob","in_app":true},{"colno":39,"filename":"https://adalite.io/js/frontend.bundle.js","function":"?","in_app":true,"lineno":20376},{"colno":24,"filename":"https://adalite.io/js/frontend.bundle.js","function":"NamedError","in_app":true,"lineno":9780}]},"mechanism":{"handled":false,"type":"onunhandledrejection"}}]},"level":"error","platform":"javascript","sdk":{"name":"sentry.javascript.browser","packages":[{"name":"npm:@sentry/browser","version":"5.22.3"}],"version":"5.22.3","integrations":["InboundFilters","FunctionToString","TryCatch","Breadcrumbs","GlobalHandlers","LinkedErrors","UserAgent"]},"event_id":"75e819c30c8c48949bd8d64cbf2f5022","timestamp":1607872825.693,"environment":"production","breadcrumbs":[{"timestamp":1607872798.587,"category":"navigation","data":{"from":"/","to":"/"}},{"timestamp":1607872798.642,"category":"ui.click","message":"div.authentication.card.initial > div.auth-options > div.auth-option.file"},{"timestamp":1607872800.272,"category":"navigation","data":{"from":"/","to":"/"}},{"timestamp":1607872800.274,"category":"ui.click","message":"section.welcome > div.welcome-footer > button.button.primary.wide.modal-button"},{"timestamp":1607872807.862,"category":"ui.click","message":"div.authentication-content.centered > a.authentication-link"},{"timestamp":1607872807.863,"category":"ui.click","message":"div.page-wrapper > div.page-inner > main.page-main > div.page-demo > a"},{"timestamp":1607872807.865,"category":"navigation","data":{"from":"/","to":"/#"}},{"timestamp":1607872809.39,"category":"ui.click","message":"div.validation-row > button.button.primary"},{"timestamp":1607872811.507,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/v2/stakePools","status_code":200},"type":"http"},{"timestamp":1607872813.313,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1607872813.644,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1607872813.911,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1607872814.18,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1607872814.468,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1607872814.714,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1607872814.903,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/info/e1b7187e73b842337272d0f509204e5c7b690284189ffaed0da74000f7","status_code":200},"type":"http"},{"timestamp":1607872815.113,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872815.331,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872815.347,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872815.352,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872815.356,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872815.525,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary","status_code":200},"type":"http"},{"timestamp":1607872815.695,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/delegationHistory/e1b7187e73b842337272d0f509204e5c7b690284189ffaed0da74000f7","status_code":200},"type":"http"},{"timestamp":1607872815.704,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/withdrawalHistory/e1b7187e73b842337272d0f509204e5c7b690284189ffaed0da74000f7","status_code":200},"type":"http"},{"timestamp":1607872815.707,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/rewardHistory/e1b7187e73b842337272d0f509204e5c7b690284189ffaed0da74000f7","status_code":200},"type":"http"},{"timestamp":1607872815.713,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/stakeRegistrationHistory/e1b7187e73b842337272d0f509204e5c7b690284189ffaed0da74000f7","status_code":200},"type":"http"},{"timestamp":1607872815.917,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872815.937,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872816.049,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872816.102,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872816.261,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/account/poolRecommendation/poolHash/92229dcf782ce8a82050fdeecb9334cc4d906c6eb66cdbdcea86fb5f/stake/0","status_code":200},"type":"http"},{"timestamp":1607872817.198,"category":"navigation","data":{"from":"/#","to":"/"}},{"timestamp":1607872817.232,"category":"ui.click","message":"nav.navbar.authed.demo > div.navbar-wrapper > button.button.secondary.logout"},{"timestamp":1607872817.7,"category":"fetch","data":{"method":"GET","url":"https://min-api.cryptocompare.com/data/price?fsym=ADA&tsyms=USD,EUR","status_code":200},"type":"http"},{"timestamp":1607872818.759,"category":"navigation","data":{"from":"/","to":"txHistory"}},{"timestamp":1607872818.847,"category":"ui.click","message":"div.modal-body. > div.modal-content > div.modal-footer > button.button.primary"},{"timestamp":1607872820.493,"category":"ui.click","message":"section.welcome > div.welcome-footer > button.button.primary.wide.modal-button"},{"timestamp":1607872824.787,"category":"ui.click","message":"div.wrap > div.page-wrapper > ul.tabinator > li.main-tab.primary > label"},{"timestamp":1607872824.818,"category":"ui.click","message":"ul.tabinator > li.main-tab.primary > input#Staking[type=\"radio\"][name=\"tabs\"]"},{"timestamp":1607872825.477,"category":"ui.click","message":"div.staking-balances-row > button.button.secondary.balance.refresh"},{"timestamp":1607872825.52,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872825.536,"category":"fetch","data":{"method":"POST","url":"https://adalite.io/api/poolMeta","status_code":200},"type":"http"},{"timestamp":1607872825.632,"category":"fetch","data":{"method":"GET","url":"https://explorer2.adalite.io/api/v2/stakePools"},"level":"error","type":"http"},{"timestamp":1607872825.677,"category":"fetch","data":{"method":"POST","url":"https://explorer2.adalite.io/api/bulk/addresses/summary"},"level":"error","type":"http"}],"request":{"url":"https://adalite.io/txHistory","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"}}}

**Comment by refi93** [comment]
resolved in #762
