### ISSUE TITLE
Sending ADA from account with less than 2 ADA results in error

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#765]
I have an account with 1.8 ADA and when I try to send 1 ADA, I get the error "Output amount too low. Minimum output amount is 1 ADA." - I understand that the change output indeed amounts to less than 1 ADA, but that's not what the error message is saying and it's likely confusing to most users. The bug probably happens anytime you try to send an amount that is less than 1 ADA smaller from the total balance of the account, so it's not specific for small balance wallets.

A possible fix would be increasing the fees to absorb the invalid change output value - indeed, that's what Yoroi does.

An alternative would be introducing a custom error message for this case, but I cannot really think of one that wouldn't be confusing to most users. And the ones that are "Cardano-savvy" and can actually understand it are probably already skilled enough to just bump up the ADA amount being sent.

![Untitled](https://user-images.githubusercontent.com/4980147/102108305-0b5f9600-3e33-11eb-8a5b-8a93250eec0b.png)

**Comment by PeterBenc** [comment]
Already fixed.
