### ISSUE TITLE
funds missing

### ISSUE THREAD

**Issue by majordomo-7** [vacuumlabs/adalite#768]
I also had a nice balance on AdaLite, went to hyperstake, and now have no balance.  
Is there recourse?

0a319dfb31e234f301b7e5254f0fa5c634d27e41dd3609a28ddb28c8b3479422

**Comment by MichalPetro** [comment]
Hello,
hyperstake was a scam. You didnt delegate your funds but you sent them to the scammer. Unfortunately, there is no way how to retrieve your funds.

**Comment by PeterBenc** [comment]
Could you check your browser history a tell us which website you visited so we can report it in case it's still on?

**Comment by majordomo-7** [comment]
no.reply@m.gcmasia.com <no.reply@m.gcmasia.com>



[ADA  XTZ gaining on today's news - what this means for your bags.txt](https://github.com/vacuumlabs/adalite/files/5703230/ADA.XTZ.gaining.on.today.s.news.-.what.this.means.for.your.bags.txt)

**Comment by majordomo-7** [comment]
the old phishing email!  dohp!
i feel gutted today, I was excited about the cardano team, i have been stacking those for two years.  
Stupid!!

**Comment by majordomo-7** [comment]
[ADA.XTZ.gaining.on.today.s.news.-.what.this.means.for.your.bags.txt](https://github.com/vacuumlabs/adalite/files/5704131/ADA.XTZ.gaining.on.today.s.news.-.what.this.means.for.your.bags.txt)

**Comment by majordomo-7** [comment]
[coindesk scam email.pdf](https://github.com/vacuumlabs/adalite/files/5704362/coindesk.scam.email.pdf)

**Comment by MichalPetro** [comment]
Sorry for that. These phishing websites created a "send" transaction  to the scammers adreas instead of a delegation transaction. This should be obvious from the data that are presented to you on the Ledger / Trezor screen.

**Comment by majordomo-7** [comment]
sorry, not sorry!  I cant believe their is no recourse or compensation for this from adalite!

**Comment by MichalPetro** [comment]
We didnt steal your funds and the funds were not stolen because of any error or bug on our wallet. We are warning users not to interact with their wallet on any other site than AdaLite.io. There are multiple warnings on our site to take precautions not to get scammed.
