### ISSUE TITLE
Reward issue

### ISSUE THREAD

**Issue by saintjay34** [vacuumlabs/adalite#772]
I had 460k ADA staked I was receiving 200-220 ada each reward (5 days) I switched to a new pool and added 500k ada to my wallet now 960k ada. my reward drops to 100 ada now?? What gives.

**Comment by MichalPetro** [comment]
Hello, what pool are you staking to now? What pool did you stake before? It would help if you can share your address with me privately at adalite @ vacuumlabs (dot) com
Also, please note, it will take 3 epochs before you see rewards for the funds you added.

**Comment by saintjay34** [comment]
Thank you for the response. Can you send me the rules so I have them on staking. I think i just need to wait my 3 epoches. Also what does ROA 30 days mean. its at 5.369%. Im in staking pool 4 saturation 64%.
Thank you for responding,
J

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
