### ISSUE TITLE
Issue trying to stake ADA on Adalite from my Nano S, General error 0x6e06

### ISSUE THREAD

**Issue by Arkelos13** [vacuumlabs/adalite#775]
When attempting to stake my ADA I receive the following error.

"Transaction rejected while signing: Ledger device: General error 0x6e06. Please consult https://github.com/cardano-foundation/ledger-app-cardano/blob/master/src/errors.h"

I first select my stake address, then I go through the process, I press delegate and it asks me to verify on my device. I initiate the transaction and then for the second verification nothing appears on the device however on screen it says please sign the transaction and then just errors when no response is received.

I have tried this with multiple staking addresses, on different browsers that are all the latest versions (Chrome and Firefox) and all my accounts are up to date on the ledger.

Any help would be appreciated.

**Comment by refi93** [comment]
Hi @Arkelos13 - could you please share with us the raw unsigned transaction? Preferably through email to preserve privacy - adalite (at) vacuumlabs.com and please also cc me (rafael.korbas (at) vacuumlabs.com) This would allow us to investigate why your tx fails on Ledger.

Here are screenshots showing how you can obtain the raw transaction body:
![screenshot](https://user-images.githubusercontent.com/4980147/103550879-d54d8900-4ea9-11eb-85f7-f8683943d59b.png)

![screenshot2](https://user-images.githubusercontent.com/4980147/103550895-da123d00-4ea9-11eb-9d68-be1980ab0f22.png)

**Comment by Arkelos13** [comment]
information sent, thank you

**Comment by refi93** [comment]
@Arkelos13 thanks, got it. I tried signing a replica of the tx you forwarded me with my Ledger Nano S and it passed - can you check the Ledger app/ firmware versions? Mine are the following:

Ledger cardano app: 2.0.4
Secure element: 1.6.1
Microcontroller: 1.12
Bootloader: 0.11

**Comment by refi93** [comment]
Also, what do you exactly mean by

> If I reduce the number of network confirmations required to just 1

Where do you reduce the number of network confirmations?

**Comment by Arkelos13** [comment]
sorry that was just a fluke.

please ignore that section of the post.

I had reduced the confirmations on my ledger app but that was just for
bitcoin, I wasn't paying enough attention to it. I am new to crypto and the
way they operate.

from what I can tell it appears that the site is timing out when requesting
authorisation from my nano device, I received the prompts for the
transaction sometimes but most of the time is is asking me to authorise but
then not showing me anything on my nano screen except three dots.

**Comment by refi93** [comment]
Then it may be the case that you were trying to initialize a transaction while Ledger was in an intermediary state from the previous transaction attempt. If the previous tx times out, I'd recommend you to unplug ledger and plug it back in so it restarts and doesn't remain in any transitional state which then causes inconsistencies and errors being reported by Ledger.

What you describe seems like connectivity issues with U2F, did you try connecting with WebUSB as well? There's a "Connect with WebUSB" button underneath the "Unlock with Ledger" button). If the Ledger device is not recognized and you are on Windows, here's a guide on how to load the required driver via a tool called Zadig: https://shapeshift.zendesk.com/hc/en-us/articles/360011307520-Replacing-Your-Driver-Using-Zadig - WebUSB should not trigger the authorisation prompts you were mentioning so the transaction should go smoothly.

**Comment by Arkelos13** [comment]
Hi,

I have tried this with both the ledger connect and the webUSB connection
and the result is the same both times. I have removed and reinserted the
nano device as well to try and reset it.

When I press delegate this appears in chrome and on my nano it asks to
start a transaction


[image: image.png]

Once I start the transaction I get the second message as follows while the
nano still just shows the 3 dots and does not ask me to verify anything

[image: image.png]

Just as I was getting these screenshots it has now allowed me to complete
the whole transaction and register my stake.

I am not sure why all the other attempts (around 15 in total) have not
registered over the past 24 hours or so.

I can close this case for now as it appears to have processed my stake,
however it does look like this might be a recurring issue, so if you need
any further information from me then please let me know.

Kind regards

**Comment by refi93** [comment]
Yes, seems like a recurring issue worth further investigation and I'm glad it finally went through. Could you please share the screenshots in github? The images attached in the email aren't appearing, unfortunately.

**Comment by Arkelos13** [comment]
I have tried this with both the ledger connect and the webUSB connection and the result is the same both times. I have removed and reinserted the nano device as well to try and reset it.

When I press delegate this appears in chrome and on my nano it asks to start a transaction


![image](https://user-images.githubusercontent.com/76918239/103566311-b7882000-4eb9-11eb-819a-ecfe257bf823.png)


Once I start the transaction I get the second message as follows while the nano still just shows the 3 dots and does not ask me to verify anything

![image](https://user-images.githubusercontent.com/76918239/103566330-c078f180-4eb9-11eb-8b44-18acf993104f.png)


Just as I was getting these screenshots it has now allowed me to complete the whole transaction and register my stake.

I am not sure why all the other attempts (around 15 in total) have not registered over the past 24 hours or so.

**Comment by refi93** [comment]
Thanks - those prompts AFAIK trigger in "U2F" mode - are you sure you clicked "Connect with WebUSB" in the beginning and do you see some different prompt in that case?

**Comment by Arkelos13** [comment]
Yeah the prompts appeared for me in both modes. I have no more ADA to retry any more movements but if I have to do any more movements in the future I will update this post.

**Comment by refi93** [comment]
@Arkelos13 I think I found the general reason why Adalite was still falling back to U2F even if you selected "Connect with WebUSB", hence getting those prompts. I launched here on our staging environment a version that fixes the behavior of the "Connect with WebUSB" button https://adalite-staging.herokuapp.com/ - could you please try that and see if you are able to connect when you click "Connect with WebUSB" and if you come across any error?

**Comment by Arkelos13** [comment]
both with logging in and triggering a delegate transaction I didn't receive the same error on the staging website so it looks like you have fixed the issue there.

As long as I connect with WebUSB there were no prompts triggered onscreen.
