### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by rockwatr** [vacuumlabs/adalite#792]
Hi there,

I've read a few of the issues relating to this and I'm hoping I'm not in the same boat and would appreciate the help.  I transferred funds from Binance to Adalite and did check webpage before following through but at the same time I do not keep my browser history.

Transaction ID
1bd299a9b3109e7cf6d832b72ab08bb8ca07d2571adbbe64d5f0c7987f200b54

I then staked in ADLT 9 but cannot find where they are now.

Any help would be great thx

**Comment by refi93** [comment]
Hi @rockwatr - the transaction you included (https://adaex.org/1bd299a9b3109e7cf6d832b72ab08bb8ca07d2571adbbe64d5f0c7987f200b54) seems to be the withdrawal from Binance - are you able to match up any of the outputs with the address that was supposed to be yours?

Is your transaction history in Adalite empty?

Also, are you logged into Adalite directly by inserting the mnemonic or with a hardware wallet?

**Comment by rockwatr** [comment]
Hi @refi93 

That is the Binance ID, It looks like I've made 2 wallets, using the mnemonic and Nano S.  I checked both wallets and out of the 19 addresses on each, the output address does not match up.

I downloaded the transaction history for both and they are empty.

Can I share the address I provided Binance safely?  Thx

**Comment by rockwatr** [comment]
Hi there,

I can close this issue, I've figured it out and it was a "me" problem.  Sorry about the wasted time, I'm learning.  Not sure if this is a common error or not but it's worth mentioning for other newbs.  I have 2 Nano S drives and since they do not hold much program memory you have to delete and reinstall to see more coins if you have multiple.  I had reinstalled the ADA app on the wrong drive...

Thanks again

**Comment by refi93** [comment]
@rockwatr glad you sorted it out, thanks for clarifying!
