### ISSUE TITLE
Pledge not met

### ISSUE THREAD

**Issue by Blubanana** [vacuumlabs/adalite#805]
I'm new to this but I staked my ADA 14 days ago and everything looked fine. It read, Pledge Met. Now after day 15 it reads, Pledge not met.  Even tho the past 2-3 Epochs it was fine.
<img width="1346" alt="Stake ADAlite" src="https://user-images.githubusercontent.com/78095280/106019474-51418800-6088-11eb-8190-177b3513b31b.png">

**Comment by xdzurman** [comment]
Hello, this was caused due to moving funds around when securing our funds, nothing to worry about :) it should be fine for now

**Comment by xdzurman** [comment]
Closing this since the pledge is OK.

**Comment by Blubanana** [comment]
Thank you!




Robert Odey

Blu Banana, Inc.

2004 Patriot Shores Lane

Westview, KY 40178

Phone: 608.333.2583
robert@blubanana.com
