### ISSUE TITLE
Check returned tx hash for Trezor when signing a transaction

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#813]
Problem: Trezor is gracefully forward compatible and it may happen that an older version of Trezor fw signs a transaction missing fields that have been added after said fw was released. See related issue in connect: https://github.com/trezor/connect/issues/751

We are already keeping a mapping of "features" to minimum version numbers but given the importance of signing the right transaction body it would make sense to add a second line of defence. Moreover it would improve the debugging experience when updating the trezor integration as it's not that obvious when Trezor successfully returns a sign tx but it's different.

Solution: Add a second line of defence in the form of verifying the tx hash returned by Trezor and throwing if it does not match (we do it already for Ledger, though that's a necessity given that it doesn't return the tx body: https://github.com/vacuumlabs/adalite/blob/720589631ecc21f4ee1494f33174359af1085b3e/app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts#L283). The error message shown to the user can even suggest that they should make sure to have the latest Trezor fw version installed.

**Comment by PeterBenc** [comment]
This is already implemented so closing this.
