### ISSUE TITLE
Ledger Nano X not being recognized

### ISSUE THREAD

**Issue by lactose** [vacuumlabs/adalite#833]
I used adalite to buy Cardano a couple weeks ago, and now when I connect my wallet it doesn't show up on "connected devices" during the connection process. 

To save time:

I unlocked it, and opened the cardano app, which said "waiting for commands" before I tried to connect.

**Comment by refi93** [comment]
Hi @lactose, Did you try the"Connect with WebUSB" functionality (the button underneath "Unlock with Ledger") as well? It's a fallback option if the default doesn't work.

To make WebUSB work properly on Windows you may need to replace your driver using a 3rd party tool called Zadig - here is a guide by ShapeShift: https://shapeshift.zendesk.com/hc/en-us/articles/360011307520-Replacing-Your-Driver-Using-Zadig - upon launching the .exe choose Nano S/X interface 2 and winUSB driver.

I would also suggest trying the following troubleshooting steps: https://github.com/vacuumlabs/adalite/wiki/Troubleshooting#general-troubleshooting-steps-you-should-try-before-contacting-us , especially making sure that no other app/website is connected to your wallet before you attempt connecting Ledger in Adalite.

And here's the general tutorial on how to use Ledger with Adalite: https://github.com/vacuumlabs/adalite/wiki/How-to-use-Ledger-Nano-S-and-Nano-X-with-AdaLite - please make sure to follow it, especially the step of having the Cardano app selected in Ledger before attempting to log into Adalite.
