### ISSUE TITLE
Ledger Nano S fails to confirm staking transaction

### ISSUE THREAD

**Issue by stakeme** [vacuumlabs/adalite#834]
I keep receiving this message when I attempt to stake and hit the confirmation button:  "Transaction rejected while signing: Ledger device: Invalid data supplied to Ledger."  I have no problems signing into the account with the Ledger.  Ledger firmware and ADA app are updated.  I have closed out of ADAlite and replugged my Ledger numerous times.  Nothing changes on Ledger screen when I hit the confirm button; it just keeps showing "Waiting for commands"

**Comment by stakeme** [comment]
I got scammed, didn't I?  I got to website from a Markets @CoinDesk email.  That linked to what appeared to be a valid Cardano Foundation website: https://cardano-foundation.us/en/news/staking-pool-launch/
And the start staking link from the foundation page sent me to: https://ada-lite.org/
Fake, huh?

**Comment by MichalPetro** [comment]
Yes, unfortunately, I am sorry :(
