### ISSUE TITLE
[question] Is there any SDK version of this?

### ISSUE THREAD

**Issue by jlindberg-oss** [vacuumlabs/adalite#835]
I'm interested in using the functionality here programmatically.
Specifically, being able to check a balance of an address, and send a payment (assemble UTXOs, sign, and submit).

Is there any good solution for that?  Thanks so much!

**Comment by refi93** [comment]
Hi @jlindberg-oss - The first tool that comes to my mind is cardano-cli: https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/cli.html - it is very low level though and you work directly with the raw keys, it doesn't support mnemonics natively.

You may also want to take a look at Adrestia: https://github.com/input-output-hk/adrestia , especially cardano-wallet: https://github.com/input-output-hk/cardano-wallet which offers a rest API through which you can programmatically check the wallet balance and make transactions. This is also the backend of the Daedalus wallet.

Both solutions require a full node running in your system. If you are looking for something lightweight that can interact with an externally hosted node, like web3 for Ethereum, I'm not aware of anything similar for Cardano, unfortunately.
