### ISSUE TITLE
Sporadic TransactionCorruped error

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#841]
We are receiving sporadic reports of TransactionCorruped errors which seem to be triggered during building of the transaction body from what seems to be an invalid/empty transaction plan.

Proposed approach: add auxiliary logging in production to check how the tx plan gets modified when the error is triggered

**Comment by PeterBenc** [comment]
This should be solved already by the mary release, I was able to reproduce it locally and fix it. If it reoccurs I ll reopen this.
