### ISSUE TITLE
Cannot transfer ADA tokens out of Ada-lite.org

### ISSUE THREAD

**Issue by Oggysweep** [vacuumlabs/adalite#842]
I am trying to transfer my ADA out of ada-lite.org

It keeps giving me the same error message:  Transaction rejected while signing: Ledger device: Invalid data supplied to Ledger

I got scammed?  Help

**Comment by MichalPetro** [comment]
Hello.
Ada-lite.org is obviously a scam phishing website. The only genue adalite domain is adalite.io

**Comment by refi93** [comment]
If you use Ledger to store the funds (as the error message suggests) and you didn't confirm the transaction on it, your funds are still safe. The scam site has no way of getting hold of your Ledger's seed/private key, or sign a transaction spending (stealing) your funds without you confirming it on the device first

**Comment by Oggysweep** [comment]
Thanks, I was able to transfer back.    Is there actually ADA staking and what is the real site to do so?

**Comment by refi93** [comment]
https://adalite.io is the only legitimate Adalite domain
