### ISSUE TITLE
Trying to move from one account to another

### ISSUE THREAD

**Issue by dogdaysunrise** [vacuumlabs/adalite#862]
Hello, I am trying to move ADA from account 1 to account 0. I keep getting the error 'Transaction rejected while signing: Operation not supported by the Ledger device, make sure to have the latest version of the Cardano app installed'

I have the latest cardano app installed. It won't even let me redelegate the stake in account 1.

**Comment by MichalPetro** [comment]
Hello,

Did you 1) update Ledger Live 2) update Ledger firmware 3) update Cardano Ledger app in “Manager” section?

We released new Cardano Ledger app on Thursday

**Comment by dogdaysunrise** [comment]
Never even noticed the update. Thank you for your quick response! This fixed the issue <3

**Comment by dogdaysunrise** [comment]
Never even noticed the update. Thank you for your quick response! This fixed the issue <3
