### ISSUE TITLE
adalite isn't recognizing Trezor T

### ISSUE THREAD

**Issue by ThisMightHelp** [vacuumlabs/adalite#869]
The T is connected and unlocked, but the connect.trezor.io site is  frozen "Loading" and adalite.io site shows "Loading wallet data..." USB is working.  Thanks for any tips.

**Comment by MichalPetro** [comment]
Hello,
Most likely some antivirus or browser security setting. Try to temporary turn of antivirus, firewall and set browser security settings to minimum.

**Comment by refi93** [comment]
You may also try the Trezor troubleshooter to determine the nature of your problem and possible solutions: https://trezor.io/support/technical/
