### ISSUE TITLE
Lost ADA?

### ISSUE THREAD

**Issue by Kennyvanny** [vacuumlabs/adalite#870]
I transferred ADA from AdaLite to Bitpanda but not realizing that the exchange recently raised the minimum amount of coins that need to be transferred.
According to BP helppages, the coins are lost.
I can see the transaction in Cardano Explorer. Can I still retrieve the coins? And how?

**Comment by refi93** [comment]
Hi, @Kennyvanny - supposing it was the legitimate Bitpanda exchange, the only way to retrieve the funds is to ask directly Bitpanda support
