### ISSUE TITLE
ux feedback: receive addresses are hidden on the "Send" page

### ISSUE THREAD

**Issue by colemickens** [vacuumlabs/adalite#873]
Hi. This might sound silly, but I'm not new to crypto, or to navigating web UIs, and I still got tripped up.

1. It's confusing that the receive addresses are on a "Send" page.
2. Unless you have the window expanded quite wide... the receive addresses are pushed down below the fold. I looked for several minutes, then went and logged into Yoroi, then came back and finally saw them.

Feel free to close, just wanted to offer up the feedback. But uh, yeah, just looked again, it feels really out of place where it is.

**Comment by MichalPetro** [comment]
Thanks, we noticed a lot of users is confused with this design and therefore we are already working on a fix.

**Comment by colemickens** [comment]
Cool. Thanks for the quick reply and thanks for working on adalite.io! :)
