### ISSUE TITLE
Missing "Pool Registration Tx" in Advanced Tab

### ISSUE THREAD

**Issue by BisonDee** [vacuumlabs/adalite#875]
Following this article, https://adalite.medium.com/cardano-stake-pool-owners-hw-support-6d9278dba0ba, I have a Tezor successfully connected, but I do not see the "pool registration transaction" in the Advanced tab. Is there a secret to unlocking this functionality?

**Comment by PeterBenc** [comment]
Hi thanks for the report, we are aware the pool registration is currently missing on the advanced tab, there are changes that need to be implemented after the mary hardfork. We are already working on it and we plan to return the pool registration this week. I ll let you know.

**Comment by BisonDee** [comment]
Thanks @PeterBenc - does this interface require that only the registration cert in is the tx (and not the pledge cert)? If this is the case, is there a recommended way or docs for signing and submitting the pledge cert as well?

**Comment by PeterBenc** [comment]
Thats right, both ledger and Trezor require the transaction to only contain the pool registration certificate. To pledge, simply delegate to pool you created.

**Comment by BisonDee** [comment]
This is probably still needed correct? Does AdaLite make this when delegating?

https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/register_stakepool.html?highlight=pledge#generate-delegation-certificate-pledge

**Comment by PeterBenc** [comment]
Yes, if you are the owner of the pool, firstly you need to sign the pool registration transaction and submit it. Once the pool is registered, delegate your funds using AdaLite to the stakepool you just created. This is the equivalent of the steps described in the tutorial you send.

**Comment by BisonDee** [comment]
Thanks so much Peter

**Comment by PeterBenc** [comment]
@BisonDee just letting you know that the pool registration is back online.

**Comment by BisonDee** [comment]
Thanks @PeterBenc. Any plans on supporting testnet :) https://testnet.adalite.io/
