### ISSUE TITLE
Incorrect ordering of tokens in the token bundle supplied to Ledger

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#877]
I just checked the code for the preparation of the token bundle for Ledger: https://github.com/vacuumlabs/adalite/blob/develop/app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts#L206 and it seems that we are not properly ordering the keys before passing them to ledgerjs which currently delegates that to the integrating party: https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/develop/docs/signTransaction.md#outputtypeaddress

Even though Adalite is sending only one token at a time, this can have impact on chainge outputs containing a mixture of tokens, as they would not be serialized in the correct order.

For guidance on how to order the keys canonically see https://tools.ietf.org/html/rfc7049 page 26

**Comment by PeterBenc** [comment]
Should be already fixed so closing.
