### ISSUE TITLE
Cypress setup

### ISSUE THREAD

**Issue by rizip1** [vacuumlabs/adalite#888]
* Create initial cypress setup as a safe haven before another planned refactoring
* Test successful login using mnemonic & transaction creation
* Ask @Siegrift for help with initial setup

**Comment by xdzurman** [comment]
closed by #912 , although some improvements could be added, such as:
- stub login (currently takes around 8s in every test)
- more in-depth testing, currently only the most critical functionality and mostly happy cases are coverred
