### ISSUE TITLE
sent Ada direct from 3rd party wallet to AdaLite Satking address 

### ISSUE THREAD

**Issue by colambo** [vacuumlabs/adalite#897]
i provided my friend with the below address which i thought is the receiver address for my adalite wallet. At the time i was looking for my receiver address the receiver window did not exist therefore i used the address shown on my main wallet padge. 
Apparently since 2 weeks i have not received my adas. 
I guess its a direct satking address but i m not 100% sure. Is that possible to sent the ada back to the sender ? Contact the Stakepool to withdrwa the ada to my wallet or any other solution ? 

addr1qxakj9qw2da0k77uznfvr5d8hahjnsfhw57l97nmde05m0q3nrutjakal8w2nt9e5v4x78pt6x07wyy8hk7v0lvwwdksndugpv

I would apprechiate any help

**Comment by refi93** [comment]
Hi @colambo , the address you listed is an ordinary address which would be your own address, if you've actually seen it in Adalite's interface. There are "staking addresses" but those are merely references to stake keys and the blockchain wouldn't even allow sending funds there directly. The address apparently received funds on March 11th:

https://cardanoscan.io/address/01bb69140e537afb7bdc14d2c1d1a7bf6f29c137753df2fa7b6e5f4dbc1198f8b976ddf9dca9acb9a32a6f1c2bd19fe71087bdbcc7fd8e736d

So if you don't see it right now you are probably logged into a different wallet than you've been logged into 2 weeks ago. Also please make sure you are and were interacting with https://adalite.io , the only legitimate website, and not some even slightly misspelled version of it as that would be some scam site

**Comment by colambo** [comment]
Hi @refi93, thank you for your promt reply. Following the cardanoscan, i see that the adas are still alive. 

I use Adalite using my Ledger. How can I decide to which wallet i want to log in ?
When I go via the tap Receive, i see that i can "verify on ledger" like 19 addresses which non of them is the address i have provided in above. 

Awaiting your instructions.

**Comment by refi93** [comment]
With Ledger you can't really decide what wallet to log in, unless you have a pasphrase set up (not to be confused with device PIN) - in that case each passphrase results in a different set of keys being generated and hence a different wallet. The implication of this is that if you mistype your passphrase, you would end up with a different wallet. You can find more on the topic here: https://support.ledger.com/hc/en-us/articles/115005214529-Advanced-passphrase-security

If you don't have a pasphrase set up, the only other way that comes to my mind is wiping the device and setting it up from a different mnemonic, or having multiple physical devices set up with a different mnemonic.

**Comment by MichalPetro** [comment]
Hey @colambo, my suggestion is to think if:

1) Are you sure you didn't use any mnemonic phrase before accessing the wallet instead of the Unlock with Ledger button?
2) Did you always open the wallet using the "Unlock with Ledger" button or you did also some other method (mnemonic?)?
3) Do you have only 1 HW wallet device? Didnt you use some other device?
4) Did you restore your Ledger using Ledger seed phrase?
5) Did you use any Ledger passphrase to protect your wallet?
6) Can you check the accounts screen to see if you have some funds on other than the first account?

**Comment by colambo** [comment]
Hi @MichalPetro  and  @refi93 

1. yes I m sure i dident use any mnemonic phrase, i have allways used my ledger to log in 
2. yes allways. 
3. I have only one HW
4. i have not restored my ledger for a while now. 
5. as far as i know not
6. i have 2 accounts , account 1 with 0 Adas but with 6.521 rewards blanace and the account#2 i have no coins. 

When i log in with my ledger i see that my ledger is exporting 2 different public keys. However all receiver accounts i see are only liked to one public key. When i try to reject one public key adalite.io cancels my process. Any advice on this ? 

Maybe when i manage to log in with my second public key i may see different wallets.

**Comment by colambo** [comment]
Hi Chicos @refi93 and @MichalPetro, 

i have updated my cadano application on my ledger, reconnected my device with adalite.io. My ledger was asking me to export 6 public keys ( wow i was impressed how many). Finally my adas are appearing on my ledger. 

Thank you very much for your quick replies and support. I hope i dont need you guys anymore :D 

have a good day. 
brgds
Colambo
