### ISSUE TITLE
Cannot delegate to valid stake pool - "Enter a valid stakepool id."

### ISSUE THREAD

**Issue by spirestaking** [vacuumlabs/adalite#900]
One of our stake pools is unavailable in adalite. When entering the stake pool ID, adalite returns "Enter a valid stakepool id."  The pool was previously retired, but has since been re-registered and is actively producing blocks with over 100 delegators.  The pool is available in Daedalus and Yoroi.

If adalite uses SMASH < 1.4.0 as its back-end, then SMASH requires an upgrade to address a bug regarding previously retired pools.

Pool ID: 248a66f38e131b6c3b6ade0a639622068f537824edeb2e9c5b107e86

Thanks,

Spire Staking

**Comment by MichalPetro** [comment]
@xdzurman

**Comment by mmahut** [comment]
Your metadata hash does not match the one registered on-chain.

```
Hash mismatch from poolId '248a66f38e131b6c3b6ade0a639622068f537824edeb2e9c5b107e86' when fetching metadata from 'https://data.spirestaking.com/ADA/c2-B.json'. Expected 3bbf756c4d210e5309c3d922e768800738f47d96648d3d80f108e5a422b3ddd1 but got f9c3451d490dce423e71d878062f407e2d8835126657668f2253e8ef0e634bf9.
```

**Comment by xdzurman** [comment]
@spirestaking Should be fixed now. Previously, we did not refresh retired pools in a good way
