### ISSUE TITLE
How do I withdraw ada from my rewards account balance to my available wallet so that i can withdraw? 

### ISSUE THREAD

**Issue by eddei1177** [vacuumlabs/adalite#901]
I have 45 ADA in my rewards account balance, when i click withdraw and it says "insufficient funds for the transaction, the minimal amount of ADA for sending the tokens is 0.000000"

how do i withdraw this ada?

**Comment by MichalPetro** [comment]
You need to have some funds on your wallet to pay for the transction fee (at least 1 ADA). You cant pay the transaction fee from the rewards balance.

**Comment by ppershing** [comment]
If we should be precise, I think you can pay transaction fee from the
withdrawal. However, the transaction has to contain at least one unspent
input due to cardano replay protection rules.

**Comment by kbodesign** [comment]
_s anyone available to review my question at this link or search on the main page with this title? I appreciate it, Thanks
Adalite Wallet & recovery phrase #906
https://github.com/vacuumlabs/adalite/issues/906#issue-839802412_
