### ISSUE TITLE
Adalite Wallet & recovery phrase

### ISSUE THREAD

**Issue by kbodesign** [vacuumlabs/adalite#906]
I was double-checking the recovery phrase I had if it would open my wallet instead of with my ledger. It opened a second wallet with nothing. I planned to take the phrases offsite to a safety deposit box for backup so I doubled checked all my passwords and recovery info to see if all was in order. Unfortunately new to this crypto world, the phrases entered into the mnemonic Adalite option opened a wallet with zero balance, and the ledger when connected opened with ADA. I have 2 wallets. 

1. Should the mnemonic option with your recovery phrase open the same wallet as when connecting with the ledger? 
2. Did I create a second wallet and write down the second recovery phrases but not the first wallets phrases? 
3. How do I correct this so I have confidence the one set of phrases opens both and I have one account?

I do believe I may have created a second by accident and have the wrong phrases since I use my ledger which opens the unprotected wallet with no backup phrases where ADA is stored. 8(

I did move everything out to an exchange for now being paranoid until this is resolved. I was wondering if I can view the recovery phrases when logged like in coinbase wallet or other wallets which is how I verified those are all correct. If not delete both wallets and start from scratch so I have verified all is correct and not let this happen again. Thanks in advance!

**Comment by refi93** [comment]
@kbodesign sorry for the delayed reply, here are answers to your questions:

> 1. Should the mnemonic option with your recovery phrase open the same wallet as when connecting with the ledger?
No - Ledger derives the keys from the mnemonic differently than Adalite or any other mainstream software wallet for Cardano

> 2. Did I create a second wallet and write down the second recovery phrases but not the first wallets phrases?
If you mean that by inserting the Ledger mnemonic into Adalite you created a new wallet, then not really. The wallet and its addresses do not "exist" on the blockchain until you deposit there any funds.

But more importantly - you should not EVER insert your Ledger's mnemonic in any computer/software as that defeats Ledger's security (the software/computer can be infected with malware which would be then able to move (i.e. steal) your funds without your consent) This is also explained in Ledger's official "best practices" article: https://www.ledger.com/academy/hardwarewallet/best-practices-when-using-a-hardware-wallet If you lose your Ledger and the funds stored there are of any significant value, it's almost always better/worth the value to just buy another Ledger device.

I would recommend you to reset your Ledger with a new seed and move all the funds (not only Cardano) stored on the old seed, as your current seed can no longer be considered secure, if you inserted it in your computer, even if it was a trusted wallet like Adalite, as it cannot be reasonably ruled out that e.g. some malware was recording the key-strokes/screen/copy-paste clipboard

If you want just to verify your mnemonic, Ledger offers a dedicated app for that: https://support.ledger.com/hc/en-us/articles/360007223753-Recovery-Check so you don't need to reinitialize Ledger or type it somewhere outside of it.

> 3. How do I correct this so I have confidence the one set of phrases opens both and I have one account?
As explained in the answer to question 2, you don't - Ledger's mnemonic is not supposed to be used/exposed anywhere else except the Ledger device itself. Other coins may be implemented differently on Ledger and the mnemonic may actually work the same on other software wallets, but if you do that, you can use those software wallets directly without Ledger as well, as its security would be defeated.

next time for support inquiries please reach us out on channels designated for that purpose (adalite@vacuumlabs.com / contact us form) as github is a development platform.

**Comment by kbodesign** [comment]
I will move everything off and follow your instructions. Never will enter phrases again unless recovering!

I think I made an error and need to write my questions clearer.

I entered not a Ledger mnemonic (recover phrases x24) but the one from Adalite into the Adalite web site which opened a seperate wallet with a 0.0000 balance. So this apparently was not an error I suspect since it did open a wallet. 

Then the ledger when connected opens to another wallet with not a zero balance but my tokens, this is correct. 
That being said the Adalite mnemonic (recovery phrases) is useless since I am using a ledger correct? 
(the ledger prompts me to export the public keys and grants me access to my wallet). 

This entire thing started because **I think** forgot to write down the adalite recovery phrases so **I think** I hit create wallet again and wrote down most likely a different set of recovery phrases. I backstepped and verify before storing my passwords away safely. The other wallets with passwords and recovery phrases are all correct. Coinbase allows you to view the phrases easily for example. On Adalite I only had one option to enter the recovery phrases under the mnemonic option on the Ada site. (hence different wallet opened up zero balance.) 
FYI my ledger phases are also verified because I have 2 using the recovery phrases and both have access to the same funds. mostly a test but will reset one soon.

I hope this is clearer. 

Thank you very much for that response. I appreciate it.

**Comment by refi93** [comment]
@kbodesign You're welcome :) Yes, you don't need to log into AdaLite with a mnemonic/create a new wallet if you have a hardware wallet, unless you want to have a separate "hot wallet". With Coinbase, I'm not sure how it exactly it works but I'd assume it stores your keys even after you close it so that's why it can show them/the passphrase to you, however Adalite is stateless which is a deliberate design decision so nothing sensitive remains in your browser storage after you leave the site.

**Comment by kbodesign** [comment]
Thanks so much for clarifying. The hot wallet is for anyone without a ledger or similar device. 
The mnemonic phrases opened a separate account with zero balance but that account or wallet will always be zero! 
That being said I am secure and no need to reset anything, this is correct?

**Comment by refi93** [comment]
>  The mnemonic phrases opened a separate account with zero balance but that account or wallet will always be zero!
Yes - a new mnemonic results in a new wallet being generated and as long as you don't send there anything, the balance would remain zero.

>  That being said I am secure and no need to reset anything, this is correct?
As long as you didn't insert the Ledger mnemonic anywhere else but the Ledger device itself then yes
