### ISSUE TITLE
Translation to Spanish language

### ISSUE THREAD

**Issue by Cardinense** [vacuumlabs/adalite#916]
Hello

I would like (if you allow me) to translate Adalite frontend to Spanish language... I just don't know how to start. Newbie on GitHub but reading a lot and learning fast.

Thanks for this excellent and beautiful wallet.
Greetings.

**Comment by Cardinense** [comment]
Please, I need some help here, where can I start the Spanish translation?

**Comment by MichalPetro** [comment]
Hello @Cardinense, I am very sorry but AdaLite is not ready to be translated. We don't have any dictionary built in. We are currently working on a new product and we may need some translators for it. We will reach out to you if we need Spanish translators.

**Comment by Cardinense** [comment]
Hello @MichalPetro, I'm sorry to hear that, but I understand. 

 I am interested in translating Cardano related products, but if you need to translate another product, I will gladly collaborate. 

Best regards.
