### ISSUE TITLE
Adalite is trying to send my ADA to a different address?!

### ISSUE THREAD

**Issue by MatsumotoEO** [vacuumlabs/adalite#923]
Just wanted to confirm if anyone else is having this issue.

I'm trying to send out some ada from my Trezor T via adalite.

There are no issues with connectivity or sending my public keys from Trezor to adalite but when sending out 5 ada to a different wallet I get a weird prompt on my Trezor.

First, Trezor prompts me if I want to send 5ada to address_A (Which is fine). I confirm and swipe to the next screen.

Second, Trezor then randomly prompts me if I want to send a totally different amount of ada to address_Z (What?!)

Am I missing something here?!

Thanks in advance!!

**Comment by MichalPetro** [comment]
Helo Mtasumoto, I see you closed this but this was probably because you didn't migrate your funds from legacy Byron addresses to the new (July 2020) Shelley addresses.
