### ISSUE TITLE
coins sent from exodus wallet never arrived in ADA Lite wallet

### ISSUE THREAD

**Issue by rinagrass** [vacuumlabs/adalite#937]
I sent 20 coins from my exodus wallet on MArch 28th and they never arrived in my ADA Lite wallet.  The transaction hash is:  32523fe1136d99881ecd0424c58e5732255b58d0bc6ee6ced9a4a0d60d1c2050   Can you please help me?

**Comment by MichalPetro** [comment]
Hello,

The funds were received and they are sitting on the address that you sent them to.

https://cardanoscan.io/address/addr1q9m9588dfs69ya592ecycf7tdshqpqkvxm2pw0alqt9urxxley85va047mjrnwe33l43zgt2mu7kq3l43ugtd5yxcc0s4y7tfe

**Comment by rinagrass** [comment]
thank you. I see them now. I think I didn't see them b/c I was trying to access the wallet via my trezor. My Adalite is a new wallet and I haven't figured out how to use it with my trezor just yet. If you have any instructions or advice on how to get my coins into my trezor that would be much appreciated. thanks.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MichalPetro** [comment]
You need to use the Unlock with Trezor link on AdaLite website. This will open your Trezor wallet.

If you created a mnemonic wallet before that and used mnemonic to open a wallet, you should transfer funds from the mnemonic wallet to your Trezor wallet.
