### ISSUE TITLE
Wallet error ADA wallet using Ledger

### ISSUE THREAD

**Issue by CamBlxck** [vacuumlabs/adalite#966]
Hello,

if anyoen could help, that would be great.  My ledger nano x is up to date for everything.  I'm trying to connect to my ADA wallet and it keeps saying there's an error and that I need the up to date firm ware.  Any suggestions?  THanks!

**Comment by refi93** [comment]
Hi @CamBlxck - could you clarify what version of the ledger Cardano app do you have, what OS/browser are you using? Also, what's the exact error message you are getting? 

First, I'd suggest you to try the general troubleshooting steps in our wiki if you didn't already: https://github.com/vacuumlabs/adalite/wiki/Troubleshooting

**Comment by divided-by-zero** [comment]
This might be related to Firefox 88.0. I just tested this on Windows and was not able to login either. Chrome still working fine.

**Comment by tylr-r** [comment]
I ran into this issue on Brave browser via a hard connection. Looks like ledger updated the ADA wallet so that may be the issue. 

Adalite gave the error:

```
Error loading wallet
DeviceStatusError: Wrong Ledger app.
```

**Comment by MichalPetro** [comment]
> I ran into this issue on Brave browser via a hard connection. Looks like ledger updated the ADA wallet so that may be the issue.
> 
> Adalite gave the error:
> 
> ```
> Error loading wallet
> DeviceStatusError: Wrong Ledger app.
> ```

Hello - I suppose you are connecting through Connect with WebUSB button. You need to open Cardano Ledger app before initiating this connection. Also make sure that your Cardano Ledger App is 2.2.0 or 2.2.1 - you can check and update this in Ledger Live > Manager section
