### ISSUE TITLE
transfer from my swyftx wallet

### ISSUE THREAD

**Issue by Age95** [vacuumlabs/adalite#977]
Hi I'm transferring my ada from my swyftx wallet to my ada lite with my ledger nano x and it's taking quite a long time, is there a reason for this?

**Comment by Age95** [comment]
I transferred to the address on Account 0 is this correct?

**Comment by MichalPetro** [comment]
Hello Age, yes this is correct, you still didn't receive your funds? It can take some time to receive funds from exchange. If you didn't receive funds, send email to our email address together with information like if you are using a mnemonic or HW wallet and include the TX id from the sender.

**Comment by Age95** [comment]
Hi Michal, I am using a ledger nano x which i'm assuming is a hardware wallet. There is no Transaction ID as yet because the status of the transfer is on pending and has been for the last 24 hours.

**Comment by Age95** [comment]
I have contacted Swyftx support to ask for a TX id number and they said they will look into it.

**Comment by MichalPetro** [comment]
If your transaction status is pending... that means the sender didn't send it yet... so only Swyft can help you

**Comment by Age95** [comment]
ok thank you i will contact them immediately
