### ISSUE TITLE
Site created a new (empty) wallet connecting to Trezor T

### ISSUE THREAD

**Issue by reetx8853** [vacuumlabs/adalite#989]
I went to look at my balance today on the site and connected with my Trezor T.  My balance is empty and I have no idea why,  Transaction history shows no transactions, and I move my coins here because I wanted the hardware wallet that works with Trezor.

**Comment by MichalPetro** [comment]
Hello.
1) do you use a passphrase to protect your Trezor? https://wiki.trezor.io/Passphrase 

2) are you sure that you didnt create a new mnemonic wallet when you have been first interacting with AdaLite? Didnt you write down a 15 word phrase back then?

3) didn't you reset your Trezor device?

**Comment by reetx8853** [comment]
I had not set up a passphrase on the Trezor until a few days ago.  

No new mnemonic when I used the Trezor to set up the wallet, just had do confirm on the Trezor.  

I have not done a reset on the Trezor

 

It does register with other wallets with no problem, just this site.

 

The coins were transferred from my Coinbase account to AdaLite, so I do have details on the transaction.

 

Thank you

**Comment by MichalPetro** [comment]
The issue will be in the Passphrase. Using a Passphrase creates a new wallet for you. Try to use blank passphrase before accessing AdaLite.

**Comment by reetx8853** [comment]
That worked!  Thank you so much!
