### ISSUE TITLE
Cardona on Ledger

### ISSUE THREAD

**Issue by aKdanFord1** [vacuumlabs/adalite#998]
Tried to get Cardona on my Ledger Nano X, but getting stuck at waiting for command. The adalite.io website keep asking to reinsert device which I do several times and nothing happens.
My NANO X version is 1.3

Is there anything else I can do?

**Comment by refi93** [comment]
What browser/operating system are you using? My first guess would be that you are on Windows and a prompt about authenticating with your key appears, so switching to Google Chrome browser and using connect with WebUSB could help.

To set up web usb on windows, you may need to use the zadig tool, it's described here: https://github.com/vacuumlabs/adalite/wiki/Troubleshooting#ledger

**Comment by aKdanFord1** [comment]
Hello,
I am using Google Chrome.

Andre
